### ISSUE TITLE
Unerreichbare Aktivität / Adress-Suffix Prüfung

### ISSUE THREAD

**Issue by dertseha** [softwerkskammer/Agora#1006]
Am 29. Juli 2015 gibt es aktuell zwei ähnliche Aktivitäten (Coding Dojo Vienna). Das Duplikat musste angelegt werden, weil die erste ein Adress-Suffix von ```%3F``` (=```"?"```) hat. Dadurch kann man sie nicht anwählen und bearbeiten.

Ich war nicht dabei als diese erste Aktivität angelegt wurde, daher weiß ich nicht, wie das Adress-Suffix zustande kam. Ausprobiert habe ich es nicht.
Die ältere Aktivität kann man löschen - und bei dem Adress-Suffix gehört vielleicht eine Prüfung hin?

**Comment by leider** [comment]
Lokal geht das. Sieht nach einem Apache Issue aus. @NicoleRauch kannst Du mal danach schauen bei Gelegenheit?

@dertseha Ich versuche mal, das Event auf 2013 zurückzuschieben, dann haben wir es zum Testen noch in der DB.

**Comment by NicoleRauch** [comment]
OK, mach ich morgen.

**Comment by leider** [comment]
@dertseha ist der gelöst? -> dann bitte mal schliessen.

Danke.

**Comment by dertseha** [comment]
@leider Tut mir Leid, ich habe das Issue nicht mehr verfolgt; Einerseits weil ich nicht wusste, dass ich das schließen sollte, andererseits finde ich auch das originale Event nichtmehr (weder in 2015, noch in 2013) um die Funktion zu prüfen.

Ich schließe somit auf gut Glück.
