### ISSUE TITLE
Teilnehmeranzahl bei Events ohne Anmeldung ausblenden

### ISSUE THREAD

**Issue by georgberky** [softwerkskammer/Agora#1031]
Ich habe eben von einem Teilnehmer das Feedback bekommen, dass es verwirrend ist, wenn wir bei einem Event auf der SWK Webseite die Anmeldung deaktivieren und dann in der Beschreibung auf eine andere Seite verweisen. 

Dann steht unten auf der Seite, dass es keine Anmeldungen gibt und dass auch keine Anmeldung möglich ist:

Bislang gibt es keine Teilnahmezusagen.
Anmeldung ist zur Zeit nicht möglich.

Könnten wir eine Option "dieses Event arbeitet mit externer Anmeldung" einbauen, dass der Hinweis oben nicht mehr angezeigt wird (oder dort ein besserer Text steht) und man stattdessen einen Link auf die externe Eventseite pflegen kann?

**Comment by leider** [comment]
Meinst Du so wie hier?
https://www.softwerkskammer.org/activities/37._Treffen_der_Softwerkskammer_Muenchen#

Dann musst Du die Teilnehmer auf 0 begrenzen und die Anmeldung aktivieren (hidden feature)

**Comment by NicoleRauch** [comment]
@georgberky Passt das jetzt für Dich? Dann mach doch bitte diesen Issue zu. Danke!

**Comment by leider** [comment]
@georgberky bitte schließen, wenns passt (siehe vorherigen Kommentar von @NicoleRauch )

**Comment by georgberky** [comment]
Ah, sorry, hab nicht gemerkt, dass hier was passiert ist. Dank euch. Das ist ok so. Muss man halt wissen :)
