### ISSUE TITLE
Wer eine Gruppe anlegt, sollte automatisch Ansprechpartner werden

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1037]
Dies scheint aktuell nicht der Fall zu sein.

**Comment by dataduke** [comment]
Danke fürs anlegen ;-)

**Comment by leider** [comment]
Ich mach das mal

**Comment by leider** [comment]
Ich kann das nicht lokal nachvollziehen. Derjenige, der "new" macht, ist automatisch als Ansprechpartner angekreuzt.

Bitte nähere Infos.

**Comment by NicoleRauch** [comment]
Das Problem ist beim Anlegen der Thüringer Gruppe aufgetreten - da war niemand Ansprechpartner. Für Details bezüglich wie das Anlegen vor sich ging: Bitte @dataduke fragen.

**Comment by dataduke** [comment]
@leider @NicoleRauch Details zum Ansprechpartner-Fall:

Ich hatte mich via GitHub eingeloggt und die Gruppe über den Link `https://www.softwerkskammer.org/groups/new` von der Help-Seite `https://www.softwerkskammer.org/help.html` aus angelegt. Nach dem Ausfüllen aller Felder sowie speichern war die Gruppe zunächst komplett leer. 

Daraufhin bin ich einfach der Gruppe beigetreten um zu sehen ob ich vielleicht hierdurch Ansprechpartner werde und war dann normales Mitglied.

Wenn es eigentlich funktioniert, würde ich vorschlagen den Fall dennoch zu schließen.

**Offtopic:**

Hätte noch ein Frage: `Name` und `Prefix for e-mail-subjects` lassen sich nachträglich nicht mehr editieren. Geht es vielleicht durch eine Datenbankanpassung oder so das Minus bei uns `jena-devs` jeweils rauszunehmen, also das Ganze jeweils zu `jenadevs` umzuwandeln? Wäre klasse für die Konsistenz da wir das jetzt überall so geändert haben. Danke.

Alternativ Gruppe löschen. Habe alle Daten offline und würde sie einfach schnell neu anlegen.

**Comment by leider** [comment]
Danke. Gruppe löschen ist ein großer Act. Im Hintergrund liegt ne Unix Mailingliste. Stört das - sehr?

**Comment by NicoleRauch** [comment]
Kannst Du nicht die Tags in der Mailingliste manuell umschießen? (das hab ich ja selbst in dem gruseligen Sympa hinbekommen...)

**Comment by dataduke** [comment]
Also falle es für die Mailingsliste zu kompliziert ist, möchte ich euch da nicht stressen ;-) 

Wichtig wäre mir zunächst überall den gleichen URL suffix `https://www.softwerkskammer.org/groups/jenadevs` zu verwenden, da wir alle Plattformen (GitHub, Twitter, Meetup) gegeneinander verlinken um zügig eine kritische Teilnehmerzahl aufbauen zu können. Hoffe das klingt plausibel.

**Comment by leider** [comment]
Muss schauen, wo der Name überall steht. Das ezmlm ist da nicht ganz straightforward. 

Aber machbar ist das natürlich schon. 

Eventuell durch ne neue Gruppe.

**Comment by leider** [comment]
@dataduke Neue Gruppe anlegen ist das einfachste. Bitte mit "J" für die Karte (Autokennzeichen)

Im Anschluß musst du dann:
1) alle events umhängen (ist wohl nur einer)
2) allen Mitgliedern (aktuell 4) Bescheid sagen, dass sie ihre subscriptions ändern
3) Die alte Gruppe solltest Du aus der Landkarte entfernen und in der Beschreibung als obsolet kennzeichnen
4) Sobald alles erledigt ist, mir Bescheid geben, ich lösche dann die alte Gruppe

**Comment by leider** [comment]
Zum eigentlichen Bug: Solange Du nicht Mitglied in der Gruppe bist, bist du auch als Ansprechpartner nicht sichtbar. - Das ist natürlich ein bissel fragwürdig, aber andererseits ist das die einfachste Möglichkeit als Superuser Gruppen zu bearbeiten, ohne Mitglied zu werden.

**Comment by NicoleRauch** [comment]
@leider : Du sagst: "Solange Du nicht Mitglied in der Gruppe bist, bist du auch als Ansprechpartner nicht sichtbar."

Aber @dataduke hatte vorher beschrieben: "Daraufhin bin ich einfach der Gruppe beigetreten um zu sehen ob ich vielleicht hierdurch Ansprechpartner werde und war dann normales Mitglied."

Passt für mich nicht zusammen?!

**Comment by leider** [comment]
Ich kann es nicht nachvollziehen.

@dataduke Bitte beim Neuanlegen nochmal prüfen, ob es diesmal geht. - Wenn nicht, bitte umgehend melden.

**Comment by leider** [comment]
@dataduke Hi, ich will ja echt nicht unangenehm sein, aber das Ganze hier würde ich gerne erledigen. Ich hasse offene Enden.

**Comment by dataduke** [comment]
@leider Hallo Andreas, sorry. Habe jetzt die Gruppe angelegt. Das mit dem Admin werden hat diesmal sofort funktioniert. :-) Habe mir diese Woche nochmal alle anderen Gruppen angeschaut und hatte dann gestern abend noch nen Meeting dazu (auch mit dem Sponsor). Hätte dazu bescheid geben sollen. Entschuldige. Du hast natürlich recht. Also wir Reihen uns jetzt quasi auch in das klassische Namensschema gerne ein. Vielen Dank für die große Geduld.

**Comment by leider** [comment]
Also doch nicht umbenennen?

**Comment by dataduke** [comment]
@leider gerade erst gesehen.

Ich hatte es so verstanden, dass die alte Gruppe (https://www.softwerkskammer.org/groups/jena-devs) nur gelöscht werden kann, da eine Veränderung von `Name` und `Prefix for e-mail-subject` zu kompliziert ist. 

Daher habe ich einfach eine neue mit den passenden Werten (https://www.softwerkskammer.org/groups/jena) angelegt, sodass die alte nun komplett gelöscht werden kann.

**Comment by NicoleRauch** [comment]
@leider: Ich habe mal alle Gruppenmitglieder aus der alten Gruppe entfernt und in die neue Gruppe eingetragen, sie sollte sich also jetzt ohne viel Durcheinander löschen lassen.

Viele Grüße
Nicole

**Comment by dataduke** [comment]
@NicoleRauch super Danke! wow, sehr nett :+1:

**Comment by leider** [comment]
Alle Spuren beseitigt.

**Comment by dataduke** [comment]
@leider @NicoleRauch herzlichen Dank für alles. Ab jetzt sollte es einfach von der Hand gehen. Bin sehr glücklich, dass alles geklappt hat!
