### ISSUE TITLE
https connection problem

### ISSUE THREAD

**Issue by dpolivaev** [softwerkskammer/Agora#1041]
https://www.softwerkskammer.org/

![2016-03-18 19_42_43-nicht gesicherte verbindung](https://cloud.githubusercontent.com/assets/1558052/13888442/c59be336-ed41-11e5-8058-51c061fd2a91.png)

**Comment by NicoleRauch** [comment]
Wow, Adleraugen! Sorry, ich war zu spät dran mit der Neugenerierung des Zertifikats. Ist jetzt wieder alles abgesichert.

Bitte prüfen und schließen.

**Comment by dpolivaev** [comment]
Thanks
