### ISSUE TITLE
Broken link in Readme.md file

### ISSUE THREAD

**Issue by Olorin71** [softwerkskammer/Agora#1045]
### File: README.md
-------  Text
The built-in wiki

To set up the built-in wiki follow these instructions
------- Text end

**Comment by NicoleRauch** [comment]
Oh, danke! Magst Du selbst fixen?

**Comment by Olorin71** [comment]
wenn du mir sagst wohin der link gehen soll.

https://github.com/softwerkskammer/Agora/wiki?

**Comment by NicoleRauch** [comment]
Hm, guter Punkt, weiß ich grad auch nicht... Sorry! @leider , weißt Du wo diese Anleitung sein sollte?

**Comment by Olorin71** [comment]
oder 
softwerkskammer/lib/wiki/README.md?

**Comment by leider** [comment]
Weiß auch nicht

**Comment by Olorin71** [comment]
ich habe es jetzt auf

softwerkskammer/lib/wiki/README.md

ist das gleiche Wert wie vorher, nur eine verzeichnisebene tiefer.
