### ISSUE TITLE
Anmeldung via GitHub

### ISSUE THREAD

**Issue by fschlag** [softwerkskammer/Agora#1054]
Beim Anmelden via Github werde ich auf die Startseite der softwerkskammer umgeleitet. Ich werde nicht wie erwartet nach persönlichen Daten gefragt oder eingeloggt.

In meinem GitHub Account wird "Softwerkskammer" jedoch als Authorized applications gelistet. Auch ein entfernen hier und ein erneuter Versuch brachten keine Lösung.

Danke!

**Comment by NicoleRauch** [comment]
Kannst Du uns ein bisschen mehr Kontext geben? Wo versuchst Du Dich anzumelden? Bei der SoCraTes? Bei der Softwerkskammer? Oder lässt Du die Applikation lokal bei Dir laufen? Wie genau meldest Du Dich an? etc. etc.
Nur dann können wir Dir sinnvoll helfen. Danke!

**Comment by fschlag** [comment]
Hallo Nicole,

na klar :-)

Will mich für folgendes Event anmelden: https://www.softwerkskammer.org/activities/socramob-2016-2

**Klicke "Ich bin dabei! (s.u.)**
![image](https://cloud.githubusercontent.com/assets/1858978/14137399/f08f144e-f667-11e5-9ed0-c09233811642.png)

_Anschließend lande ich auf folgender Seite:_
![image](https://cloud.githubusercontent.com/assets/1858978/14137434/15b16768-f668-11e5-9e81-6198ec4294b5.png)

**Klicke auf "Anmelden"**
_es folgt_
![image](https://cloud.githubusercontent.com/assets/1858978/14137462/36be0524-f668-11e5-9cc5-8329d2c7e830.png)

**Klicke auf "GitHub"**
_lande auf der Startseite, nicht eingeloggt._
![image](https://cloud.githubusercontent.com/assets/1858978/14137508/5c39f830-f668-11e5-9831-23eb0439cd2e.png)


Meine GitHub Account Einstellungen bekommen durch dieses vorgehen jedoch einen OAuth Eintrag:
![image](https://cloud.githubusercontent.com/assets/1858978/14137577/a270f2b8-f668-11e5-9d23-73c6963623a5.png)


Hoffe das hilft schon. 

VG,
Florian

**Comment by NicoleRauch** [comment]
Na klar, das hilft, danke! Wir schauen mal, ob wir mehr über das Problem rauskriegen können.

**Comment by grossh** [comment]
Hi, 
genau der gleiche Effekt tritt bei der Anmeldung über Google auf. Man landet immer auf der Startseite der Softwerkskammer. Auch ein Login dort führt nicht zum Ergebnis, sprich der Status bleibt Gast.

Viele Grüße
Harald

**Comment by NicoleRauch** [comment]
Ist das Problem jetzt behoben?

**Comment by grossh** [comment]
Über Google kann ich mich jetzt wieder an der Softwerkskammer und bei der Socrates anmelden. Aus meiner Sicht ist das Problem behoben.
Vielen Dank
Harald

**Comment by fschlag** [comment]
Funktioniert wieder. Dankeschön!
