### ISSUE TITLE
Anmeldung schlägt fehl.

### ISSUE THREAD

**Issue by GeDo432** [softwerkskammer/Agora#1055]
Hallo. Ich kann mich nicht mit Firefox oder Chrome anmelden: Nachdem ich Google+ oder Github ausgewählt habe, Lande ich immer auf der Startseite. Ich konnte keine persönlichen Daten eingeben.

**Comment by NicoleRauch** [comment]
Ist das Problem jetzt behoben?

**Comment by GeDo432** [comment]
yep. weg ist es. Danke!

2016-03-30 18:32 GMT+02:00 Nicole Rauch <notifications@github.com>:
