### ISSUE TITLE
Profil zeigt SoCraTes only Bild, aber Gruppen sind subscribed

### ISSUE THREAD

**Issue by leider** [softwerkskammer/Agora#1062]
Die SoCraTes only Erkennung ist wohl kaputt

![profil](https://cloud.githubusercontent.com/assets/450708/14423515/8740df80-ffdc-11e5-9c51-ba8bbb6bb034.PNG)

**Comment by NicoleRauch** [comment]
Sorry, ich brauch ein bisschen mehr Kontext ...

Du bist in der SWK, bist dort eingeloggt, und schaust Dein Profil dort an?

**Comment by NicoleRauch** [comment]
Und was genau ist Dein Problem? Was siehst Du, und was erwartest Du?

**Comment by leider** [comment]
Ich glaube, die SoCraTes Registrierung hat das gemacht.
