### ISSUE TITLE
gc/ram etc

### ISSUE THREAD

**Issue by sebs** [softwerkskammer/Agora#1064]
![Jo](https://cdn.meme.am/instances/500x/67866202.jpg)

So I took a look at the gc problem but didn't deep dive.

The problem seems to be: GC not kicking in, memory grows. 
Possible given broken things: jade+express piling up refs to templates. 

How to solve this? 
Basically a bit of code stretching. 

The thing with gc related stuff its programmer miss conduct + gc bugs/missing features. So my half assed educated guess would be some options: 

* If it reacts to a global.gc(); https://simonmcmanus.wordpress.com/2013/01/03/forcing-garbage-collection-with-node-js-and-v8/ 
  * The guys from strongloop did some good stuff presenting on this topic and writing a lot of posts. TL;TR setTimeout(gc)
* https://nodejs.org/api/v8.html setFlagForString - Its a trap 
* Move on with node releases. 5.9.0 has proven to be very useful. 
  * looks like the patch grunt plugin should be a problem. Just use a shellscript and the shellscript plugin from grunt. I would be in moving things around in that repo as long as we need to get a recent node version running. 
* node --v8-options - Have fun reading docs.

**Comment by NicoleRauch** [comment]
Ein paar Gedanken und Fragen von mir hierzu:

> The problem seems to be: GC not kicking in, memory grows. 

Wir machen doch nur ne echt kleine Geschichte hier, keinen nennenswerte Last und so. Und trotzdem solche Probleme? Wie geht es denn dann erst "richtigen" Applikationen?

> given broken things: jade+express piling up refs to templates.

Haben die echte, bekannte Bugs? Sollten wir uns hier lieber etwas anderes überlegen?

> a bit of code stretching

Was meinst Du hiermit genau?

> programmer miss conduct 

Und was meinst Du damit genau?

> Move on with node releases. 5.9.0 has proven to be very useful.

Die neueste Version, die uns aktuell zur Verfügung steht, ist 5.7.1. Hilft uns das?

Danke schonmal für Deine Tipps und Ideen!

**Comment by sebs** [comment]
> Wie geht es denn dann erst "richtigen" Applikationen?

Einfach, sehr einfach. Halt auch sehr einfach einen bug einzubauen. Selbst oder in den Modulen. Die denke mit dem Scoping und State führt in der Node ecke dann doch oft zu eher funktionalen Konstrukten.  Das wenn es schnell gehen soll. Und wenn Zeit ist, so wie bei express. Dann kann man das mit Events machen. Wobei diese Abweichung vom "Purismus" mit dem ganzen Syntax Zucker dann halt auch Klassen und den unbedachten Eisatz von State betrifft. Events+state. Auch nicht so toll. 

> Haben die echte, bekannte Bugs? Sollten wir uns hier lieber etwas anderes überlegen?

Das Szenario ging nur aus dem Gespräch mit @leider hervor. Der meinte das Restartet sich mit memory max immer wieder per Providerdekret.  . Die beiden Tools sind ok. Wenn man jade abkann und express mag. Beides schon oft eingesetzt. So viel so schlauere Dinge gabs noch nicht. Mit neuen releases mitrollen sollte man aber. Jade ist jetzt pug. Wusste ich auch nicht.  

Euch fällt da bisschen die ein Repo keine Module Strategie auf die Füsse, das amcht den Prozess nur langsam. Ein zwei divide and conquer Lininen im Sand  würde ich vermissen. Es hat schon lange gedauert bis es ding grün gemacht hat ;) Nur darum ist das testen und ansehen da schwer. 

> Die neueste Version, die uns aktuell zur Verfügung steht, ist 5.7.1. Hilft uns das?

Nein, weil das repo nicht drauf läuft und ich es dir nicht garantieren kann. Ich habe nur, nach dem 5.6.0 in  meinem Projekt Ruhe. Ich hab grad performance tests gemacht und irgendwie den Eindruck mitgenommen: Es hat sich was getan und ist der Last angemessener mit weniger hoch runter Phänomen. 

So generell: Probiert mal das mit der gc per hand. Da ists vielleicht davon abhängig wann und wie und wo ihr das macht. Zur Peaktime wirds andere Auswirkungen haben als im Standardbetrieb. Aber so im generellen Betrieb. Wenn das geht: Das sind 20 Minuten, "löst" das Problem und ihr könnt das repo bissle auseinander ziehen. Dann kann man sowas wirklich einfach tunen und untersuchen ;) 

Was auch geht: http://pm2.keymetrics.io/docs/usage/cluster-mode/ + ein ram max definieren. Ich kenne ja die Kiste nicht. Ich optimier so gern an den Unsauberkeiten von modul und node devs rum. 

Verbastelt doch in eurem Start skript was das auf SIG* hört.
http://joseoncode.com/2014/07/21/graceful-shutdown-in-node-dot-js/

So macht man sowas tatsächlich erst mal zu einem ops Problem. Müsste halt nur den State in der Anwendung einsammeln und alles ordentlich zu machen (Datenbanken, payment etc). Damit ist das Ding einfacher verwaltbar. Es muss ja nicht alles sein, nut halt ein Signal um den Server zum organisierten Rückzug zu bewegen. 


Grüße
Dr. Tut das Node.js das Sie hier so spät noch posten?

**Comment by NicoleRauch** [comment]
Update to Node.js 6 fixed this.
