### ISSUE TITLE
Kann nicht auf Mail antworten, obwohl..?

### ISSUE THREAD

**Issue by draptik** [softwerkskammer/Agora#1065]
Kann nicht auf Themengruppe antworten, obwohl ich ne Mail bekommen habe 

Hi. This is the qmail-send program at monoceres.uberspace.de.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<testing@softwerkskammer.org>:
Sorry, only subscribers may post. If you are a subscriber, please forward this message to testing-owner@softwerkskammer.org to get your new address included.

Ich bin Subscriber. Und darf nicht Posten.

Was muss ich machen?

**Comment by leider** [comment]
Die Diskussion wird privat weitergeführt.

**Comment by NicoleRauch** [comment]
Wie ist denn jetzt hier der Status? Sind noch Fragen / Probleme offen?

**Comment by draptik** [comment]
Issue kann geschlossen werden

2016-04-30 23:40 GMT+02:00 Nicole Rauch <notifications@github.com>:
