### ISSUE TITLE
redundant user profile

### ISSUE THREAD

**Issue by andreasgrimm** [softwerkskammer/Agora#1068]
somehow I managed to create 2 separate user profiles.
`https://www.socrates-conference.de/members/andreasgrim` which I can edit and which is connected to my github account and which has no picture
and there's `https://www.socrates-conference.de/members/andreasgrimm`, which I can not edit but which has the correct avatar picture.

I guess I somehow messed with the system during last nights registration issue going on.

I'd like to go with `andreasgrimm` as the nickname. Maybe you can merge the 2 accounts or delete one so that I can edit my nickname :)

Thanks in advance!

**Comment by NicoleRauch** [comment]
You simply logged in with two different authentication providers: 
Github login produced andreasgrim and Google login produced andreasgrimm.
The avatar picture is determined from the email address, which is also different for the two accounts (we require that).
I have deleted the andreasgrim profile. I hope that is what you wanted :-) If so, please close this issue.

**Comment by NicoleRauch** [comment]
Hi Andreas,

wie ist denn hier der Status? Bist Du jetzt zufrieden mit deinem Profil, oder sollen wir hier noch was für Dich anpassen?

Wenn ersteres -> bitte Bug schließen
Wenn letzteres -> lass mal hören :-)

**Comment by NicoleRauch** [comment]
Scheint sich geklärt zu haben...
