### ISSUE TITLE
Anmelden nur OAuth möglich / Mail-Adresse bereits vergeben

### ISSUE THREAD

**Issue by AlexZeitler** [softwerkskammer/Agora#1088]
Hallo,

ich bekomme seit einigen Tagen Mails von den SWK-Mailinglisten.
Ich hatte mich vor einigen Jahren auch registriert.
Allerdings kann man sich nur noch über OAuth z.B. via GH anmelden.
Wenn ich versuche, mich per GH zu authentifizieren und verwende meine alte E-Mail-Adresse, heißt es, dass diese (logischerweise) bereits verwendet wird.

Eigentlich möchte ich mich nur einloggen, um mich von den Mailinglisten abzumelden.

**Comment by NicoleRauch** [comment]
Hi Alexander,

Du hattest Dich damals mit Google Plus authentifiziert. Wenn Du Dich wieder mit Google Plus einloggst, solltest Du ganz normal in Deinem Account landen und die Mailadressen abbestellen können.

Hoffe, das hilft Dir.

Viele Grüße
Nicole

**Comment by AlexZeitler** [comment]
Danke Nicole, via Google+ hat es jetzt funktioniert 👍

**Comment by NicoleRauch** [comment]
Und welchen Deiner beiden Accounts darf ich jetzt löschen, nachdem Du Dich ein zweites Mal registriert hast?

**Comment by AlexZeitler** [comment]
@leider hat das schon erledigt - Danke :)

**Comment by NicoleRauch** [comment]
Perfekt :-)
