### ISSUE TITLE
error 500 when editing profile, fields room mate or remarks

### ISSUE THREAD

**Issue by rmgit** [softwerkskammer/Agora#1100]
edit profile : https://www.socrates-conference.de/members/edit
enter "someone who: wakes up early, doesn't plan to party long, doesn't snore" into field "Who do you want to share your room with:"
save
-> error 500

edit profile : https://www.socrates-conference.de/members/edit
enter "vegetarian/vegan into field "Remarks (e.g. dietary restrictions):"
save
-> error 500

**Comment by NicoleRauch** [comment]
Thanks! I'll look into it asap.

**Comment by NicoleRauch** [comment]
I think it works again now. Can you please try and confirm or complain again? ;-)

Thanks,
Nicole

**Comment by rmgit** [comment]
It works
Thanks for your work
