### ISSUE TITLE
Error 500 when trying to login using Google OAuth

### ISSUE THREAD

**Issue by redsteve** [softwerkskammer/Agora#1101]
2016-08-21, 12:50 am

A login attempt using Google OAuth results in an error message "500 - failed to obtain access token (Error: getaddrinfo EAI_AGAIN www.googleapis.com:443)".

## Stacktrace:

InternalOAuthError: failed to obtain access token at node_modules/openidconnect-for-passport/lib/strategy.js:100:38 at node_modules/oauth/lib/oauth2.js:177:18 at ClientRequest.<anonymous> (node_modules/oauth/lib/oauth2.js:148:5) at emitOne (events.js:96:13) at ClientRequest.emit (events.js:188:7) at TLSSocket.socketErrorListener (_http_client.js:306:9) at emitOne (events.js:96:13) at TLSSocket.emit (events.js:188:7) at connectErrorNT (net.js:1015:8) at _combinedTickCallback (internal/process/next_tick.js:74:11) at process._tickCallback (internal/process/next_tick.js:98:9)

## OS/Browser:

Windows 10 (Version 10.0.10586) + Google Chrome Version 52.0.2743.116 m

**Comment by NicoleRauch** [comment]
Currently, the server where Softwerkskammer and SoCraTes are hosted is under attack (for some hours now, I think) - please see https://twitter.com/ubernauten/status/767212277724577792 and https://twitter.com/ubernauten/status/767267625181339649 and https://twitter.com/ubernauten/status/767291186117771264 . I suspect that your error is related to this attack. Please try again later...

**Comment by leider** [comment]
No further complaints received
