### ISSUE TITLE
Update README: remove vagrant instructions

### ISSUE THREAD

**Issue by coderbyheart** [softwerkskammer/Agora#1102]
Vagrant is no longer officially supported by the Agora project.

**Comment by pas2al** [comment]
We should not remove it, we should keep it up to date ;-)

**Comment by NicoleRauch** [comment]
Well, the problem with "we should" is that in the end nobody does it. At least that's how it went since we were given this vagrant file.

**Comment by pas2al** [comment]
Thats the reason why we are making a workshop on the Socrates right now and i would love to do it (or at least try it ;-))

**Comment by NicoleRauch** [comment]
Great! Then I'm looking forward to your rephrased message, starting with "I want" instead of "We should" ;-)

**Comment by NicoleRauch** [comment]
Nevertheless, I sincerely ask you to switch the order of descriptions in the README: Even if the vagrant solution works again, it is NOT the preferred way of installing and running Agora. None of the Agora core team is able or willing to support this. Over the past 2-3 months I've got at least 3 messages starting with "I'v tried to run Agora, but the vagrant stuff does not work". And I cannot help them. Therefore, for me the vagrant solution is a backup if the other stuff does not work, not the other way around.

**Comment by pas2al** [comment]
Ok. It depends. I work with Vagrant quite often and i always try to make it as simple as possible, because i don't want to spam my local environment with configs and installations. Nevertheless i will have a look on both.

**Comment by NicoleRauch** [comment]
I understand that people who are familiar with Vagrant like to use it. On the other hand, it imposes so much more hassle when working with the code (e.g. debugging) that I would rather not promote it to a newbie.
