### ISSUE TITLE
Groom or delete Backlog

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1107]
There is a very old backlog for this project at https://github.com/softwerkskammer/Agora-Backlog/issues

Do we want to keep any of its contents any more? Or should we delete it altogether?

**Comment by coderbyheart** [comment]
Well, I don't know the answer to that, but I would like to have one place which I consult to see, what I should work on. Ideally there are *starter*-Issues (well defined, not very complicated) and/or *quickfixes*, so new contributors (like myself) can get started easily.

**Comment by leider** [comment]
Great ideas. - Is Trello a suitable solution?
- integrate with github
- categorize by complexity _and_ importance (2 dimensions)

**Comment by coderbyheart** [comment]
I <3 Trello, but … GitHub issues are perfectly fine. If you need more dimensions, use [milestones](https://guides.github.com/features/issues/#filtering) or projects (a new feature), that works like Trello: https://www.youtube.com/watch?v=C6MGKHkNtxU

**Comment by leider** [comment]
Could / Should we do a hangout where we can talk about it? @NicoleRauch @coderbyheart and me.

If you know more interested parties, feel free to invite them

**Comment by NicoleRauch** [comment]
The separate backlog (in a different github repo) did not contain anything any more, therefore I deleted it.
