### ISSUE TITLE
Remove heapdump

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1108]
as we have fixed the memory issues.

Should we then also move the C++ documentation to an "optional" section?
(Because we might introduce new modules that require it again...)

**Comment by leider** [comment]
- Does it really seem to be fixed?
- Is that the last C++ module?

**Comment by NicoleRauch** [comment]
No memory overruns any more since we upgraded to Node 6. This matches my definition of "seems to be fixed" :-)

I did not see any other C++ modules. Of course this should be double-checked after removal.

**Comment by leider** [comment]
from my side it can be closed

**Comment by NicoleRauch** [comment]
Thanks!
