### ISSUE TITLE
Cannot add editors

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1110]
When trying to add an editor to an activity of the Karlsruhe group, I get an empty dropdown:

![image](https://cloud.githubusercontent.com/assets/436499/18036666/98e5bc30-6d71-11e6-8cf6-ea0cff904115.png)

**Comment by leider** [comment]
Are there Participants?

**Comment by NicoleRauch** [comment]
Oh, you mean editors must be participants first? Fair point...

Then let's turn this issue around: We need to improve the UI so that this becomes clearer ;-)

**Comment by NicoleRauch** [comment]
Or maybe we should change the behaviour to: "Editors can be selected from the members of the group." Or "...from the members of the group AND the current participants."

Because currently it is often a two-pass thing to make somebody an editor, which is a bit annoying... (first create the activity, then ask the wannabe-editor to sign up, then make them an editor).

What do you think?

**Comment by leider** [comment]
Agree with it

**Comment by leider** [comment]
Rethinking this, I believe it should not be done:
* when creating a new activity, the assigned group is still unknown, thus we do not know which potential editors to display
* for editing it would be clear unless the group was changed
* the "real" / elegant implementation would load the potential editors async or allow for manual assignment via nickname - both would require significant effort to develop

Any other ideas?

**Comment by leider** [comment]
Answer to previous comment:
* make the field editable
* enter known nickname there

Fulfills requirement.

**Comment by leider** [comment]
solved by #1114
