### ISSUE TITLE
Dashboard: No line breaks in wiki page window on Mac / Firefox

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1123]
On Mac / Firefox, the wiki page contents is not wrapped. (On Chrome, everything looks fine.)

![bildschirmfoto 2016-09-18 um 20 56 37](https://cloud.githubusercontent.com/assets/436499/18618669/afa51a8a-7deb-11e6-8f08-d85f5808a96f.png)

**Comment by NicoleRauch** [comment]
Submitted by Till Rauch who wins a prize for the first bugreport on the Dashboard ;-)

**Comment by leider** [comment]
Please enter more details (versions)

**Comment by leider** [comment]
Firefox 34.0.5 (mac) looks fine.

**Comment by NicoleRauch** [comment]
This screenshot was taken on 48.0.2 (Mac) ...

**Comment by leider** [comment]
any proposals on how to deal with that? - I don't think we can easily influence rendering quirks.

**Comment by leider** [comment]
Mit aktueller Version (49.0.2) nicht mehr aufgetreten. Schließe daher.
