### ISSUE TITLE
Erneute Anmeldung im Profil ist nicht möglich

### ISSUE THREAD

**Issue by zf2timo** [softwerkskammer/Agora#1124]
Guten Tag,

ich habe mich vor einiger Zeit auf der Seite Softwerkskammer.org angemeldet um an einer Veranstaltung teil zu nehmen. Dafür habe ich die Google Authentifizierung verwendet.

Da ich mich jetzt für eine weitere Veranstaltung registrieren wollte, war ich wieder auf der Seite der Softwerkskammer und musste feststellen, dass es keinen Link zum anmelden gibt.
Alle Links führen zur Registrierung-Seite, in der mir auch angezeigt wird, dass meine E-Mail Adresse bereits vergeben ist.

Daher meine Frage, wie ich mich erneut auf der Website anmelden kann, damit ich mich für eine Veranstaltung registrieren kann.

**Comment by leider** [comment]
Mehr Details bitte.

**Comment by zf2timo** [comment]
Wenn ich oben rechts auf `Profil` klicke und dann auf `Anmelden` kommt ein Popup zum auswählen des Authentifizierung Provider.
Dort wähle ich `Google` aus und lande auf einer Seite um ein neuen Account anzulegen. Das habe ich aber bereits getan und möchte mich mit meinem bestehenden Account anmelden.

**Comment by NicoleRauch** [comment]
Du hast Dich beim letzten Mal mit Github authentifiziert. Probier's mal damit und sag Bescheid, ob es geklappt hat.

**Comment by zf2timo** [comment]
Das hatte ich dann wohl falsch in Erinnerung, dass ich Google verwendet habe.

Dann ist aber die Meldung auf der Seite zum Registrieren, sehr verwirrend. Dort wurde automatisch meine E-Mail Adresse von Google eingetragen, mit einer Fehlermeldung, dass diese bereits verwendet wird.

**Comment by NicoleRauch** [comment]
Das ist ein schwieriges Problem, in der Tat. Wenn Du sagst, Du möchtest Dich mit Google authentifizieren, haben wir keine Chance, Dich mit Deinem existierenden Profil in Beziehung zu setzen. Deswegen der "Neues Profil"-Dialog.

Wir holen von den OpenID Providern ein paar Daten und füllen das Profil schonmal ein bisschen aus, um es den Registrierenden leichter zu machen. Bei Google hast Du anscheinend dieselbe Mailadresse hinterlegt wie bei Github. Daher haben wir bei der ersten Registrierung dieselbe Mailadresse eingetragen wie jetzt auch.

Ich bin gerade am Überlegen, ob die Software beim Auswählen des "richtigen" Providers irgendwie unterstützen kann. Denn Du bist bei weitem nicht der Einzige, der sich nicht mehr an den Provider erinnern kann...

**Comment by zf2timo** [comment]
Eventuell reicht schon den Text etwas abzuändern. 
`Diese Adresse ist schon registriert. Hast Du bereits ein Profil angelegt? Verwendest du die Adresse bei einem anderen Provider?`

**Comment by NicoleRauch** [comment]
Ich habe ein neues Issue angelegt für den Beschreibungstext. Da Dein ursprüngliches Problem ja gelöst ist, mache ich dieses Ticket zu.
