### ISSUE TITLE
SoCraTes Management pages must ignore empty fields on submit

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1130]
When changing some information for a participant (e.g. length of stay or type of room) it is possible to submit an empty value (from the drop-down). This will then be transformed into an event, which causes all sorts of weird things to happen. So, empty or otherwise nonsensical values must be detected as early as possible and must be discarded.

**Comment by NicoleRauch** [comment]
Github did not notice that PR https://github.com/softwerkskammer/Agora/pull/1158 mentioned this bug...

**Comment by NicoleRauch** [comment]
@leider Ich bräuchte hier mal ne Verifikation - das ist ja ein Bug, den Du "entdeckt" hast ;-P

**Comment by leider** [comment]
will do

**Comment by leider** [comment]
checked
