### ISSUE TITLE
Indicate which provider the user already used

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1131]
I imagine that we store in the browser cookie which authentication provider(s) somebody has used for Softwerkskammer/SoCraTes. On the next login attempt, the login screen should indicate the previous choice(s). This will hopefully help to reduce the number of support requests for people who are trying to log in with the wrong provider.

**Comment by coderbyheart** [comment]
That only helps if you use the same browser on the same device.

What I'm missing from the description is the explanation why this is needed.

**Comment by NicoleRauch** [comment]
Yes, of course, it would not be perfect. But it would be a start.

I tried to describe why this is needed here: "This will hopefully help to reduce the number of support requests for people who are trying to log in with the wrong provider."

I should additionally point out that this currently is the number 1 support request. Also, ~1% of people created two accounts (which I think happened accidentally).

**Comment by NicoleRauch** [comment]
If you have other ideas of how to establish that, I'm of course happy to hear about them!

**Comment by leider** [comment]
We could check on submit if we find potential duplicates and then ask "there is another user with your name authenticated by github. Are you sure you want to create a new account?"

**Comment by coderbyheart** [comment]
Yeah, that's what I thought about, too. GitHub has multiple email addresses, those could be checked against, too.

**Comment by NicoleRauch** [comment]
This is nice! And also not perfect, because the feedback comes quite late in the cycle (after the user has filled in their dialog - sigh) and might be bogus for all those with "common" names. (We already have 2x2 persons with identical names in SWK.) Also not safe to compare the names if the user spontaneously decides to write the name differently - like, we have so many ppl in SWK whose last name is "." :-) 

So, ideally, I'd like to have both - and I personally would go with the frontend indicator first.

**Comment by NicoleRauch** [comment]
The Github-multiple-email-check thingie would be a nice extension to #1127 I think.

**Comment by NicoleRauch** [comment]
My suggestions have been implemented. Is anybody interested in also having the other suggestions? These are:

* We could check on submit if we find potential duplicates and then ask "there is another user with your name authenticated by github. Are you sure you want to create a new account?"
* GitHub has multiple email addresses, those could be checked against, too.

**Comment by leider** [comment]
I'm happy with the current improvement. What about you @coderbyheart ?

Things to maybe address in a new issue:

- mention the use of cookies generally 
- showing the last login may be regarded as a privacy issue

**Comment by NicoleRauch** [comment]
I'm closing this now because there were no further comments. Feel free to open another issue for further improvements.
