### ISSUE TITLE
Make "desired roommate" field more visible

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1133]
Last year, many people did not fill in the "desired roommate" field - instead they put their favourite into the "remarks" field. This is not helpful for the management screens because they selectively use parts of the provided information in different areas.
The idea is to make the field more prominent and visible so that people are more inclined to putting the right information in the right field.

**Comment by leider** [comment]
I propose a layout re-arrangement and additional validation (e.g. field is mandatory if user has selected a double room) 
![preview](https://cloud.githubusercontent.com/assets/450708/21590724/7f643a98-d0fe-11e6-92f6-9bd2377e43b8.jpeg)

**Comment by NicoleRauch** [comment]
Hm, I don't think it makes sense to make the field mandatory. Not everybody knows somebody to share the room with, or they only arrange for that long after registration. So a mandatory field would only increase the noise (ppl just write something random, this is not helpful in the management UI).

**Comment by NicoleRauch** [comment]
For the rearrangement, I'm not sure if your proposed solution makes the field more visible or more invisible... There is this huge "remarks" field next to it that seems to dominate the whole section. Hard to tell without seeing the full screen, though.
On the other hand, moving the field closer to the others feels like an improvement to me.

**Comment by leider** [comment]
I agree on both pints. Making the field mandatory is my approach to make it more visible as it is red then! - Of course people may fill in something random but at least they have seen **there is a field** for the roommate.

**Comment by NicoleRauch** [comment]
Understood. Still I think it's a horrible UX ;-)
So I would like to come up with something better tbh.

**Comment by leider** [comment]
The whole page or just this field?

**Comment by leider** [comment]
Guess that is fair enough now
