### ISSUE TITLE
Automate the lottery process

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1136]
The lottery process is very time consuming as we were using real randomness from https://www.random.org/ , and we had to count the participants in the list manually.

An automated process would look something like this:

For a given room type and a given number of users that should be admitted, do the following:
- Determine how many users are in the lottery (i.e. everybody who submitted before the deadline)
- Get a random number from random.org (do they provide an API?) or some other reliable source of randomness
- Admit the randomly picked user
- Repeat until the desired number of users has been admitted

This mechanism should only work for a single room type to allow more fine-grained control of the lottery.

**Comment by agnyp** [comment]
Das würde ich mir gerne schnappen.

**Comment by NicoleRauch** [comment]
Cool :-) Es gibt schon ein Node-Modul zur Anbindung von Random.org, habe ich letztens gesehen. Das sollte eigentlich schon alles tun.

**Comment by agnyp** [comment]
Großartig. Hatte dort gesehen, dass sie eine API anbieten, aber gleich auch noch ein Framwork ... :-)

**Comment by NicoleRauch** [comment]
Das ist von irgendwem anders, ich glaube es heißt node-random oder so. Wirst Du schon finden ;-)
