### ISSUE TITLE
minor css flaw in some line breaks: Dashboard - Upcoming Activities 

### ISSUE THREAD

**Issue by skonair** [softwerkskammer/Agora#1146]
The new dashboard has an upcoming activities section in the upper left corner.
On some devices and some resolutions, the group name is not shown correctly and moved below without resizing the surrounding cell. See attached screenshots from a Linux/Firefox 48.0 and Android 5.1.0/Chrome 52.0.2743.98
![screenshot_2016-09-22-22-46-23](https://cloud.githubusercontent.com/assets/3167633/18775423/eb1428da-8161-11e6-9dad-a2e4c998b111.png)
![bildschirmfoto vom 2016-09-23 07 28 19](https://cloud.githubusercontent.com/assets/3167633/18775422/eb100c6e-8161-11e6-8f42-35e60814cc11.png)

**Comment by leider** [comment]
Thanks for reporting. Do you have an idea what the cause could be? Or even how to fix it? Or maybe can fix it and place a pull request?

That would be great!

Did you experience the behaviour on some other platform? Especially desktop platforms would be great for reproduction. 

Technically we are using plain bootstrap for styling. Maybe we are using it in an unsuitable way?

**Comment by skonair** [comment]
@leider On a first glance I didn't find the cause of the behaviour. 
To reproduce you can use Firefox and scale up and down the text size (and maybe subscribe to a group with a long name like Münster, Osnabrück, Bielefeld).

But I will have a closer look today.

**Comment by leider** [comment]
Great! Thanks a lot

**Comment by skonair** [comment]
I found one entry for this issue in the web. It looks like the 'clearfix' css class will help us here, when used together with the class 'list-group-item'. On Linux/Firefox it now looks good. I will try to test on Android and create a pull request later.

**Comment by NicoleRauch** [comment]
I've deployed your change - could you please verify and then close this bug?

(And thanks again for the good and quick work on this!)

**Comment by skonair** [comment]
Page https://www.softwerkskammer.org/dashboard/ checked with Mac/Firefox and Android/Chrome. Looks good.

Incredible deployment time.
