### ISSUE TITLE
I cannot login anymore with using Google as open id provider

### ISSUE THREAD

**Issue by Fischermaen** [softwerkskammer/Agora#1157]
Why? I can only use Google+ now, but this doesn't lead me to my old account, it'll open a new one. So therefore I would prefer having an own account for softwerkskammer, how can I migrate my old one to a new one?!?

**Comment by leider** [comment]
Create a new one and send me a pm afterwards. I then will merge your profiles

**Comment by NicoleRauch** [comment]
Did you merge the profiles by now @leider ? Can this issue be closed?

**Comment by Fischermaen** [comment]
Dear Nicole and Andreas,

Profiles are merged, login is working and issue can be closed. Thanks for
your effort.

Andy

Nicole Rauch <notifications@github.com> schrieb am So., 9. Okt. 2016, 22:30:

**Comment by NicoleRauch** [comment]
Thanks for your quick reply @Fischermaen :-)
