### ISSUE TITLE
Editing somebody else's profile breaks the interests

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1163]
When I (as a Softwerkskammer administrator) edit somebody else's profile, the list of interests only contains one entry (in the edit screen) even if the person has multiple entries.

(When I edit my own profile, I see all interests, though).

**Comment by leider** [comment]
Ursache klar: bei vielen ist da noch ein whitespace dabei, weswegen die array trennung schiefgeht. Jetzt ran an den fix.
