### ISSUE TITLE
rename group dortmund

### ISSUE THREAD

**Issue by leider** [softwerkskammer/Agora#1186]
"dortmund" soll umbenannt werden in "ruhrgebiet"

- aktuell können Gruppen nicht umbenannt werden

**Comment by leider** [comment]
Das Ganze ist komplizierter als man auf den ersten Blick denkt:

1. die Gruppen werden als "ezmlm"-Gruppen gespeichert https://de.wikipedia.org/wiki/Ezmlm
1. die Mailhistorie ist natürlich an der Gruppe
1. die alten Activities beziehen sich auch auf die Gruppe
1. der Gruppenname ist primary key (das ist das technische "Problem" dahinter)

Ich schlage vor, eine neue Gruppe anzulegen. Wir können dann versuchen, die subscriber mit einem script zu übertragen.

**Comment by NicoleRauch** [comment]
Hm, meinst Du wirklich? Das haben wir doch mit Sympa auch schonmal hingekriegt...

**Comment by leider** [comment]
Also ezmlm ist da echt sperriger. Wir könnten:

- Die neue Gruppe anlegen
- Alle Members dorthin umziehen (unsubscribe / subscribe über javascript)
- dann alle referenzen in den activities ändern und dem mailarchiv
- das wiki umbenennen
- die alte ezmlm Gruppe löschen

Die ersten beiden Schritte sind MUST, das danach ist m.E. nice-to-have

**Comment by leider** [comment]
Fallen dir noch andere Seiteneffekte ein?

**Comment by leider** [comment]
Die ezmlm "Datenstrukturen" sind generiert und voll von Literalen des Gruppennamens in dateinamen sowie -inhalten

**Comment by NicoleRauch** [comment]
Ja, klingt ganz gut
