### ISSUE TITLE
When searching wiki, search parameter should be escaped

### ISSUE THREAD

**Issue by leider** [softwerkskammer/Agora#1195]
Error: Command failed: git --git-dir=/home/swk/Agora-Wiki/.git --work-tree=/home/swk/Agora-Wiki grep --no-color -F -n -i -I andreas leidig
fatal: ambiguous argument 'leidig': unknown revision or path not in the working tree.

**Comment by NicoleRauch** [comment]
Oopsi :-)

I can have a look into this tomorrow.

Nicole
