### ISSUE TITLE
Discuss

### ISSUE THREAD

**Issue by leider** [softwerkskammer/Agora#1197]
ramda vs. lodash:

Aktuell haben wir (oder sind noch dabei) lodash durch ramda ersetzt. Dies hat trade-offs:

1. lodash ist sehr spezialisiert auf collection operationen und hat ein streaming ähnliches interface. Dadurch liest es sich in einigen Situationen extrem gut.
1. ramda ist (näheres ist noch zu evaluieren) langsam bei bestimmten operationen. Beispiel `union` zweier listen, von denen eine mehr als 1400 members enthält

bitte mal meinungen

**Comment by NicoleRauch** [comment]
Wenn man die Admin-Memberlist in der Softwerkskammer anschaut, ist das schon extrem langsam...

**Comment by leider** [comment]
Das mit dem `union` war ein Implementierungshoppla.

So bleibt nur noch Punkt 1

**Comment by NicoleRauch** [comment]
Gibts hier noch Diskussionsbedarf?
(Ich find Ramda cool :) )

**Comment by leider** [comment]
Ich persönlich finde für collections das lodash API angenehmer, aber jetzt wo es umgestellt ist, alss uns dabei bleiben
