### ISSUE TITLE
google maps changed the geocoding algorithm

### ISSUE THREAD

**Issue by leider** [softwerkskammer/Agora#1214]
As of now the formerly working addresses (e.g. Walhalla, Augartenstraße 27, Karlsruhe) do not return a result when asked for by the googlemaps geolocation API. The entry works when used directly as an input inside maps.google.com.

Not funny. I don not know a way to get around this newly introduced limitation.

Therefor I propose to include the map inside the edit-activity page to have the editor see the effect of his location entry directly.

Opinions?

**Comment by NicoleRauch** [comment]
Fixed.
