### ISSUE TITLE
Calendar does not show anything

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1278]
I suspect something went wrong with the most recent version bump?

**Comment by leider** [comment]
Will Look Wednesday. Until then possibly switch back to old version of fullcalendar and patch file

**Comment by NicoleRauch** [comment]
This is weirder than I thought. Here are some observations:

#### No global issue:
- In Prod, only the activity calendar is affected, not the conference calendar.

#### Activity does not come back locally:
- Locally, I went back to fullcalendar 3.2.0, created an activity, and it was visible in the calendar.
- I then went forward to 3.3.0, and the activity disappeared.
- I went back to 3.2.0 again, and the activity did **not** come back.

#### Activities don't come back in prod:
- In Prod, I went back to fullcalendar 3.2.0, but the activities did **not** come back.

**Comment by leider** [comment]
current state: working?

**Comment by NicoleRauch** [comment]
yes, with the old version

**Comment by NicoleRauch** [comment]
why did it take 5-10 minutes after server start to work?

**Comment by leider** [comment]
caching of frontend javascript

**Comment by NicoleRauch** [comment]
even locally? hm...

**Comment by leider** [comment]
locally works for me
with 3.3.0

**Comment by NicoleRauch** [comment]
wait 10 minutes and check again

**Comment by NicoleRauch** [comment]
ok, this is fixed with the new fullcalendar version. Phew :-)
