### ISSUE TITLE
Keine Vorauswahl von Gruppen bei der Anmeldung

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1322]
Opt-In ist rechtlich sicherer...

**Comment by leider** [comment]
Ich würde diesen Issue gerne Umwidmen:
- Profilseiten erklären deutlicher, was es mit den Gruppen auf sich hat
- Gruppen stehen dort auch mit listname und emailpräfix

**Comment by leider** [comment]
![extended groups view](https://user-images.githubusercontent.com/450708/39395271-ef75d02c-4adc-11e8-870e-ec7c37656e83.jpeg)

**Comment by NicoleRauch** [comment]
Damit sind alle Punkte dieses Issues erledigt.
