### ISSUE TITLE
Magic Links implementieren?

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1331]
Wäre das eine Lösung für uns?

https://medium.com/one-more-thing-studio/how-to-make-magic-links-with-node-1d164c036e29

Wo gibt es da noch Lücken? Was deckt dieses Verfahren nicht ab, das wir brauchen?

**Comment by leider** [comment]
Klingt auf den ersten Blick plausibel und machbar.

**Comment by NicoleRauch** [comment]
Die Grundfunktionalität ist drin. Für den Rest mache ich ein neues Issue.
