### ISSUE TITLE
DSGVO - Article 15 - Right of Access by the Data Subject (What do you know about me)

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1334]
-> Die verantwortlichen muessen auf Anfragen Antworten (c't Zitat: "Laut Artikel 12 bedeutet das innerhalb eines Monats nach Eingang des Antrages")

Was können wir hier tun?

Das Profil zeigt schon viel von dem, was wir über den Benutzer wissen. Das sollten wir vervollständigen, so dass dort wirklich alle Infos über den Benutzer angezeigt werden.
(Aktuell fehlen z. B. die Mails.)

Folgende Informationen haben wir über die Mitglieder: (die abgehakten Infos werden beim Anschauen des Profils angezeigt)

* [x] Nickname, Vorname, Nachname, Twitter Handle, Region, Beruf, Interessensschwerpunkte, Website
* [x] Mitgliedschaft in Gruppen
* [x] Für welche Gruppe bin ich Ansprechpartner
* [x] Teilnahme an Aktivitäten
* [x] Mailadresse (nur beim Bearbeiten)
* [x] Authentifizierungsmethode(n) (nur beim Bearbeiten)
* [x] Benachrichtigungseinstellung für Wikiänderungen (nur beim Bearbeiten)
* [x] Wie ich von der SWK erfahren habe (nur beim Bearbeiten)
* [x] Erstellung / Bearbeitung von Wikiseiten
* [x] Für welche Aktivität bin ich Organizer
* [x] Für welche Aktivität bin ich Editor

**Comment by leider** [comment]
Zustimmung - Löschen des Mailarchivs sollte hier auch Konformität schaffen. - Im Wiki steht noch der Nickname bei den Commits

**Comment by NicoleRauch** [comment]
Oh, guter Punkt. Wie bekommen wir den denn raus? Erster Schritt wäre sicherlich, ihn für abgemeldete Mitglieder nicht mehr anzuzeigen, egal ob er noch in Git vorhanden ist.

(Anders gefragt: Fällt ein Nickname unter "persönliche Daten")?

**Comment by leider** [comment]
Ich plädiere für "Nickname ist nicht pers. Daten"

**Comment by NicoleRauch** [comment]
Im Schnitt stimme ich Dir schon zu, aber für manche ist der Nickname schon sowas wie der "Ersatzname" - da ist der Übergang dann fließend...
Schwierig.
Ich denke, wenn wir irgendwas in der Richtung machen könnten, wäre das hilfreich. (Wahrscheinlich als Stufe 2.) Und es kann vermutlich nur die Anzeige betreffen, oder? Denn ich würde ungern jedesmal Git rewriten, wenn jemand austritt...

**Comment by leider** [comment]
Hier könnten wir eine Blacklist von Nicknames einführen, wenn jemand seinen Nick nicht mehr bei uns sehen will. - Das aber nur auf Anforderung, wenn jemand das verlangt. Grundsätzlich ist es ein Stück Text, das - wenn das Member gelöscht ist, ins Nirwana führt

**Comment by leider** [comment]
- bin gespannt wie github mit sowas umgehen will... -

**Comment by leider** [comment]
Ich denke, Erstellung/Bearbeiten von Wikiseiten sind keine pers. Daten

**Comment by NicoleRauch** [comment]
Ich sehe das Thema nicht nur beschränkt auf persönliche Daten, sondern wie im Titel vermerkt "what do you know about me". Wir haben ja gerade die Anzeige der Nicknames aus der Wiki History für Ausgetretene unterdrückt, also gehört für mich im Umkehrschluss das Auflisten dieser Seiten zu den Dingen, die ich über eine Person weiß.
