### ISSUE TITLE
DSGVO - Article 17 - Right of erasure / to be forgotten

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1336]
-> Wir müssen alles löschen, sobald jmd. sein Profil loescht.

Passiert aktuell nicht für Mails. Da steht immer noch der Name drin, auch wenn jemand ausgetreten ist.

Kann man natürlich drüber diskutieren, dass das sowieso eine quasi-öffentliche Information ist. Aber vielleicht sollten wir den Benutzer auch einfach aus den Mails löschen und "ehemaliges Mitglied" reinschreiben oder so?

Wie ist das bei Teilnahme an Aktivitäten? Wird da auch ein ausscheidendes Mitglied gelöscht?

**Comment by leider** [comment]
Die Liste der Mails ist m.E. betroffen, da stimme ich zu. - Das ist allerdings schwieriger als es zunächst aussieht, da wir es hier mit existierenden Daten zu tun haben. Hier könnten wir alle "mails" löschen, die als sender eine unbekannte memberid haben. - Danach gibt es nur noch das "Zitate" Problem. - Antworten mit Vollkopie.
Einzige Möglichkeit, hier sicher zu sein -> Keine Mailarchive mehr führen. Da in Mails alles mögliche stehen kann, ist das prinzipiell juristisch sowieso grenzwertig. - Ich würde das bevorzugen

Aktivitäten referenzieren per ID, Falls Member nicht gefunden wird, wird nix angezeigt. - Aus meiner Sicht alles in Ordnung, keine Rückschlüsse auf Identität durch uns möglich, da ID künstlich und ohne Referenz wertlos. - Eventuell sollten wir mal testen, was passiert, wenn der Organizer eines Events austritt, ob wir damit zurechtkommen oder abstürzen :)

**Comment by NicoleRauch** [comment]
Wie gesagt, ich vermute nicht, dass wir den *Inhalt* der Mails löschen müssen (oder?). Meine Annahme wäre, dass es reicht, den Benutzernamen zu löschen.

**Comment by leider** [comment]
Aber der Klarname könnte im Text vorkommen.

**Comment by NicoleRauch** [comment]
Und wie schon im anderen Issue angemerkt: Im Wiki steht noch der Nickname bei den Commits.

**Comment by leider** [comment]
Der Nickname sagt leider nix aus, da ein nicht vorhandener NIckname auch entstehen kann, weil jemand seinen nich ändert...
Und was sollten wir dann mit dem Eintrag machen?

**Comment by NicoleRauch** [comment]
Well, das war *deine* Anmerkung... ;-)
https://github.com/softwerkskammer/Agora/issues/1334#issuecomment-388616903

**Comment by leider** [comment]
Ich schlage vor, bis auf weiteres einfach das Mailarchiv zu deaktivieren. Dann können wir in Ruhe entscheiden, was wir damit machen wollen.

**Comment by NicoleRauch** [comment]
Ich hab gerade mal in die Logs geschaut. Die mir vorliegenden Logs enthalten 568706 Zugriffe, davon beginnen 626 Zugriffe mit "GET /mailarchive/"

Ich würd sagen das Feature kann weg ^^

**Comment by leider** [comment]
Dann baue ich das aus. Löschen können wir die Mails später. Was meinst Du?

**Comment by NicoleRauch** [comment]
OK, also für das Entfernen des Mailarchivs sehe ich folgende Tasks:

[ ] Deaktivieren des Cronjobs
[ ] Entfernen des Codes (Anzeige + Parsing)
[ ] Löschen der DB-Collection

Passt das soweit?

**Comment by NicoleRauch** [comment]
Dann brauchen wir noch was wegen des Wikis:

* [ ] Ausblenden von Benutzerinformationen für die Einträge, die von ausgetretenen Mitgliedern erstellt wurden

Und noch mal so nebenher:

* [ ] Test, was passiert, wenn ein Organizer einer Aktivität austritt

**Comment by leider** [comment]
Was meinst Du mit dem ersten Punkt?

**Comment by NicoleRauch** [comment]
Immer noch das:
https://github.com/softwerkskammer/Agora/issues/1334#issuecomment-388616903
;-)

"Erster Schritt wäre sicherlich, [den Nickname] für abgemeldete Mitglieder nicht mehr anzuzeigen, egal ob er noch in Git vorhanden ist."

**Comment by leider** [comment]
D.h. nickname in der memberdb suchen und bei nicht finden nicht anzeigen?

**Comment by NicoleRauch** [comment]
Ja, genau. Das sollte ja sowieso nur die .../index Seite betreffen, denke ich (oder?)

**Comment by NicoleRauch** [comment]
Da kann man dann ja "N.N." anzeigen oder "ehemaliges Mitglied"

**Comment by leider** [comment]
ne, betrifft die History.

ich würde dann "N.N." schreiben -> mach ich als nextes

**Comment by NicoleRauch** [comment]
Sorry, ich hab den falschen Teil der URL abgeschrieben ^^
Ich meinte /wiki/versions/...
Meintest Du das auch?

**Comment by leider** [comment]
Ich denke, wir brauchen keine Tests für den owner und die Editors einer Activity, weil beide über IDs an der Activity hängen und diese on-demand über den memberstore geladen werden und in nicknames übersetzt werden. Bei nicht Finden passiert hier nix und der PUG code berücksichtigt dieses.

**Comment by NicoleRauch** [comment]
OK, gut. Ich hatte das nur aufgegriffen, war ja Deine Idee ;-)

**Comment by NicoleRauch** [comment]
Ich denke dann sind wir soweit durch mit diesem Issue. Ich mache es mal zu. Wenn noch jemandem was einfällt, bitte ein neues Issue machen.
