### ISSUE TITLE
Mailsender-Form <-> successURL

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1357]
Das Mailsender-Form erwartet eine successURL, die aber nirgends gesetzt wird.
Dies sollte in der einen oder anderen Art repariert werden.

**Comment by leider** [comment]
Die successURL wird gesetzt in mailsender/index.js und mailsenderService.js an verschiedenen Stellen.

Ich kann nicht folgen... Brauche mehr Kontext

**Comment by NicoleRauch** [comment]
Ah, jetzt, ja. Sorry mein Fehler!
