### ISSUE TITLE
Login redirect broken

### ISSUE THREAD

**Issue by pfichtner** [softwerkskammer/Agora#1369]
When opening an event page after authenticating (via github) I'll got not redirected to the event page but to softwerkskammer's main site.

**Comment by leider** [comment]
I belive that 720c3f9c6a785be6c88b30f5f696a01da2074523 broke it. Removal of the functionality inside   function setReturnOnSuccess(req, res, next) { probably is the root cause. It slipped also through code review...

Will try to analyse in the next days
