### ISSUE TITLE
Datumswerte fehlen auf der Webseite

### ISSUE THREAD

**Issue by anrichter** [softwerkskammer/Agora#1380]
Die aktuelle Version der Webseite zeigt keine Datumswerte an. 

Der Veranstaltungskalender ist leer, auf der Seite einer Regionalgruppe steht unter Letzte Aktivitäten nur Invalid DateTime und beim Bearbeiten eines Events zeigen die Felder für Start und Ende auch nur Invalid DateTime an.

![grafik](https://user-images.githubusercontent.com/72196/49248127-4a237e80-f419-11e8-905c-34437d795494.png)

**Comment by NicoleRauch** [comment]
Vielen Dank für das schnelle Feedback und Entschuldigung! Wir haben zurückgerollt und gucken uns das in Ruhe nochmal an.
Ich mach diesen Bug dann mal zu - bis zum nächsten Anlauf ;-)

**Comment by leider** [comment]
So, jetzt sollte es passen. git wieder auf master / HEAD. @anrichter Dir nochmals vielen Dank für den bugreport und das Feedback

**Comment by anrichter** [comment]
Passt. Sieht gut aus 👍
