### ISSUE TITLE
Event von Meetup kopieren bringt Fehler

### ISSUE THREAD

**Issue by anrichter** [softwerkskammer/Agora#1385]
Hi,

ich habe gerade versucht, ein auf Meetup angelegtes Event mit dem entsprechenden Button auf der Gruppenseite in Agora zu kopieren. Das hat leider nicht funktioniert. Ich erhalte als Antwort nur einen Proxy Error. 

Die MeetupURL ist imho richitg eingetragen. (Regionalgruppe Magdeburg)

Viele Grüße
Andreas

PS: Ich erfasse das Event jetzt erstmal per Hand, falls ihr noch mal checken wolltet.

**Comment by NicoleRauch** [comment]
Hi Andreas,
danke für den Report, ich guck mir das mal an.

**Comment by NicoleRauch** [comment]
Hey, da hast Du einen klassischen Bug gefunden - vielen Dank! Ich war naiverweise davon ausgegangen, dass in Meetup immer ein Veranstaltungsort angegeben ist... Du hast mich eines Besseren belehrt ;-) Fix ist gerade deployt. Ich lass Dir die Freude, selbst auf den Kopier-Knopf zu drücken :-D

Viele Grüße,
Nicole

PS: Ist ja sonst nicht so meine Art, aber diese Meetup-Anbindung ist echt noch im Alpha-Status oder so... Also wenn Du noch mehr Merkwürdigkeiten findest oder irgendwelche Vorschläge hast, immer her damit ;-)

**Comment by NicoleRauch** [comment]
Wie ich sehe, hat's jetzt geklappt :-) Dann mach ich hier mal zu.

**Comment by anrichter** [comment]
Jepp. Funktioniert soweit. Leider kommt der Ort nicht mit.

**Comment by NicoleRauch** [comment]
Das war ja der Grund, warum das ganze Ding auseinandergeflogen ist XD

Die Meetup Doku sagt dazu: "The event venue, present only if selected and not hidden by an organizer"
- vielleicht hilft Dir das ja weiter.

**Comment by anrichter** [comment]
Moin Nicole




Das habe ich schon verstanden.


Ich habe in Meetup ein monatliches Serien Event ohne Ortsangabe angelegt. Wenn das kommende Treffen eingeplant wird, bearbeite ich Text und Ort für das kommende Event. 




So auch jetzt geschehen. Für Januar habe ich Ort und Inhalt überarbeitet. Dann in Agora auf den Import geklickt, ohne dass dort Events für 2019 hinterlegt waren.




Da kam erst der Proxy Error. Nach deinem Fix hat der Import funktioniert, jedoch ohne Ortsangabe für das Januar Event. Die folgenden Events sind korrekt ohne Ortsangabe in Agora importiert.




-- 


Andreas Richter


Software Craftsman & Architect


http://www.anrichter.net







On Mon, Jan 7, 2019 at 10:51 PM +0100, "Nicole Rauch" <notifications@github.com> wrote:












Das war ja der Grund, warum das ganze Ding auseinandergeflogen ist XD


Die Meetup Doku sagt dazu: "The event venue, present only if selected and not hidden by an organizer"

vielleicht hilft Dir das ja weiter.

**Comment by NicoleRauch** [comment]
Hi Andreas,

ich glaube, der zweite Teil der Doku ist relevant für Dich hier: "and not hidden by an organizer"

Denn wenn ich auf Euer Event in Meetup gehe, sehe ich nur:

![image](https://user-images.githubusercontent.com/436499/50820767-cae56c80-132d-11e9-9f16-9d9ef3b5876f.png)

Die Agora ist nun auch kein Mitglied und kann daher den Veranstaltungsort auch nicht sehen...

**Comment by anrichter** [comment]
Hi Nicole

danke für deine Recherche. Mir ist bisher noch gar nicht aufgefallen, dass der Veranstaltungsort nur für registrierte Mitglieder sichtbar ist. Nu muss ich erstmal gucken, wie ich das ändern kann...
