### ISSUE TITLE
Neu registrieren mit eMail und Passwort geht nicht

### ISSUE THREAD

**Issue by dirk-olmes** [softwerkskammer/Agora#1387]
Als Teil der Anmeldung zum SoCraMOB habe ich versucht, mit ein Konto mit eMail und Passwort anzulegen. Das Konto existiert noch nicht und die Anmeldung schlägt fehl.

- Aufruf von https://www.softwerkskammer.org/activities/socramob-2019-1
- Unten auf der Seite den "Ich bin dabei!" Button klicken
- "Bitte authentifiziere Dich!" -> "Anmelden" Button klicken
- Auswahl von "Mit E-Mail und Passwort:" und "Neu anmelden"
- eMail Adresse und Passwort eingeben
- Klick auf Anmelden

Die nächste Seite zeigt "Authentifizierungsproblem authentication.error_member_exists !". Es kommt aber keine Bestätigungsmail, dass ein Account angelegt wurde, noch wird angemeldet.

**Comment by leider** [comment]
Die Meldung (die leider anscheinend nicht übersetzt ist, oops) besagt, dass Du (oder jemand anders?) mit der von Dir gewünschten E-Mail Adresse bereits bei uns registriert ist.
Als Administrator sehe ich hier auch einen Eintrag, der auf Dich schliessen läßt. - Wenn Du willst, schicke ich Dir eine E-Mail direkt an diese Adresse für weitere Hilfe. Genauere Informationen werde ich nicht öffentlich hier in github posten.

Gruß,
Andreas

**Comment by dirk-olmes** [comment]
Peinlich, peinlich, dass ich mich bereits registiert hab, das aber nicht in meiner Passwort Datenbank steht. Für weitere Infos direkt an meine eMail Adresse wäre ich sehr dankbar.

Danke,
-dirk

**Comment by NicoleRauch** [comment]
> Peinlich, peinlich, dass ich mich bereits registriert hab, das aber nicht in meiner Passwort Datenbank steht.

Hi Dirk, das ist nicht peinlich, sondern ganz natürlich, da wir bis vor kurzem nur Authentifizierung über OpenID und OAuth hatten und Du von daher gar kein Passwort setzen konntest.
