### ISSUE TITLE
Anzeigereihenfolge von Blog-Artikeln

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1389]
Diese sollten in umgekehrt chronologischer Reihenfolge angezeigt werden.

Bei der Gruppe KA ist darüberhinaus was kaputt: Da wird ein Artikel (vom 8.3.17) nicht chronologisch eingereiht...

**Comment by leider** [comment]
DAs Verhalten ist nicht mehr sichtbar
