### ISSUE TITLE
Bitte einmal Activities löschen

### ISSUE THREAD

**Issue by anrichter** [softwerkskammer/Agora#1392]
Hi,

ich habe die Verknüpfung der SWK Magdeburg zur Meetup-Gruppe gelöscht, da für mich die Integration aus verschiedenen Gründen nicht zufriedenstellend funktioniert. (Siehe u.a. #1388 und #1385).

Da ich in Meetup ein Serien-Treffen angelegt habe, hat die Synchronisierung im Agora bis zum März kommenden Jahres Activities angelegt, welche ich selber nicht bearbeiten oder löschen kann. 
Darum die Bitte einmal folgend aufgeführten Activities der Gruppe Magdeburg zu löschen:

Zukünftige Activities (Adress-Suffixe):
* [ ] [meetup-qgvggpyzhbsb](https://www.softwerkskammer.org/activities/meetup-qgvggpyzhbsb)
* [ ] [meetup-qgvggpyzjbpb](https://www.softwerkskammer.org/activities/meetup-qgvggpyzjbpb)
* [ ] [meetup-qgvggpyzkbmb](https://www.softwerkskammer.org/activities/meetup-qgvggpyzkbmb)
* [ ] [meetup-qgvggpyzlbrb](https://www.softwerkskammer.org/activities/meetup-qgvggpyzlbrb)
* [ ] [meetup-qgvggpyzmbnb](https://www.softwerkskammer.org/activities/meetup-qgvggpyzmbnb)
* [ ] [meetup-qgvggpyznblb](https://www.softwerkskammer.org/activities/meetup-qgvggpyznblb)
* [ ] [meetup-qgvggpyzpbqb](https://www.softwerkskammer.org/activities/meetup-qgvggpyzpbqb)
* [ ] [meetup-qgvggpyzqbnb](https://www.softwerkskammer.org/activities/meetup-qgvggpyzqbnb)
* [ ] [meetup-rktnpqybccbsb](https://www.softwerkskammer.org/activities/meetup-rktnpqybccbsb)
* [ ] [meetup-rktnpqybcdbpb](https://www.softwerkskammer.org/activities/meetup-rktnpqybcdbpb)
* [ ] [meetup-rktnpqybcfbnb](https://www.softwerkskammer.org/activities/meetup-rktnpqybcfbnb)
* [ ] [meetup-qgvggpyzgbmb](https://www.softwerkskammer.org/activities/meetup-qgvggpyzgbmb)

Doppelte Events der Vergangenheit (Adress-Suffixe):
* [ ] [meetup-qgvggpyzgbmb](https://www.softwerkskammer.org/activities/meetup-qgvggpyzgbmb)
* [ ] [meetup-qgvggpyzdbqb](https://www.softwerkskammer.org/activities/meetup-qgvggpyzdbqb)

Vielen Dank für eure Mühen.

Die besten Grüße
Andreas

**Comment by leider** [comment]
Done. Bitte mal checken. :)

**Comment by anrichter** [comment]
Perfekt. Vielen Dank für die schnelle Hilfe!

Ein schönes WE & die besten Grüße
Andreas
