### ISSUE TITLE
Allow to change room marketplace info later and/or to go to the marketplace before "registration"

### ISSUE THREAD

**Issue by jongleur1983** [softwerkskammer/Agora#1398]
For Socrates2019 I wanted to have a look at the room marketplace.
The profile page has a field to describe oneself, but I was sure I'd be able to change that later and left it blank. Could go to the market place but didn't find a way to change the description later.

This should either be mentioned somehow or it should be possible (and linked) to inspect the room marketplace without fixating that description first.

In my case I hoped to see what others write there to know what they may be interested in before sharing rooms.

**Comment by NicoleRauch** [comment]
Sorry, the SoCraTes organization and software is now standalone and not related to Agora any more. Please report this issue at the appropriate place (I don't know where that is, though...)
Thanks, Nicole
