### ISSUE TITLE
E-Mail-Footer für über Agora versendete Mails

### ISSUE THREAD

**Issue by UrsMetz** [softwerkskammer/Agora#1428]
Wie heute mit @leider und @signed besprochen, wollen wir als Dankeschön für unseren zukünftigen Mailprovider allen über Agora versendeten Mails einen Footer mit dem Hinweis auf den Provider hinzufügen.

Vor dem Wochenende komme ich vermutllich nicht dazu, dann könnte ich aber mal einen Versuch starten. @leider @signed Oder sollen wir uns vorher nochmal per Videotelefonie besprechen?

**Comment by UrsMetz** [comment]
Meine Vermutung7Vorschlag ist, dass man den Footer am besten in den beiden Templates
* `softwerkskammer/lib/mailsender/views/mailtemplate-textonly.pug` und
* `softwerkskammer/lib/mailsender/views/mailtemplate.pug`
oder wäre eine andere Stelle besser?

**Comment by leider** [comment]
Genau so war das gedacht :)
