### ISSUE TITLE
Problem mit Anmeldung per E-Mail

### ISSUE THREAD

**Issue by caichinger** [softwerkskammer/Agora#1439]
Bisher habe ich mich per E-Mail und Passwort angemeldet, das ist mir derzeit nicht möglich, weil keine entsprechenden Eingabefelder angezeigt werden.

Egal ob ich auf "Mit E-Mail und Passwort", ..., "Authentifizierungsmethode vergessen? Hier gibt's einen Magic Link" klicke, es gibt keine Eingabefelder (Firefox, Chrome und Opera).

![image](https://user-images.githubusercontent.com/16005912/124252890-c0377700-db27-11eb-84bf-4368252c3cdb.png)

Neuregistrierung via GitHub scheint zu klappen, allerdings ist habe ich ja schon einen Account (was auch korrekt erkannt wird, wenn ich mich mit meiner bereits hinterlegten E-Mail-Adresse neu registrieren möchte).

Bitte um Info ob ich hier etwas falsch mache bzw. was ich anders machen kann, so das Problem bei mir liegt.

Danke für das tolle Projekt!

**Comment by leider** [comment]
Wäre cool, wenn wir das außerhalb GitHub weiterführen. Schick mir ne Mail über die softwerkskammer.

**Comment by caichinger** [comment]
Klar, gerne per Mail. Ich finde leider keine Mailadresse von dir (und für https://www.softwerkskammer.org/members/leider müsste ich eingeloggt sein).

Bitte schreib Du mir an skhzu2dzbmc@temp.mailbox.org und dann setzen wir da fort. Danke.

**Comment by leider** [comment]
bitte review / confirm / close

**Comment by caichinger** [comment]
Wunderbar, Problem gelöst. Danke für die schnelle Reaktion.
