### ISSUE TITLE
Problem mit Datum und Uhrzeit beim Anlegen einer neuen Aktivität

### ISSUE THREAD

**Issue by caichinger** [softwerkskammer/Agora#1441]
Beim Anlegen der Aktivität mache ich folgende Angaben punkto Datum und Uhrzeit:

![image](https://user-images.githubusercontent.com/16005912/124349253-81b8bf80-dbee-11eb-80e3-fe3e79473021.png)

Nach dem Speichern erhalte ich aber *January 1, 1970 (01:00 - 01:00)*:

![image](https://user-images.githubusercontent.com/16005912/124349290-a6149c00-dbee-11eb-9660-41ef06af7eb0.png)

**Comment by leider** [comment]
Cool, danke für den Fehler. Ich such ihn und fix dann. Bis dahin: Auf Deutsch sollte es gehen

**Comment by leider** [comment]
Anscheinend sind da noch EINIGE bugs drin wegen Bootstrap 5.

**Comment by leider** [comment]
Anscheinend parsen wir immer deutsch (oops): https://github.com/softwerkskammer/Agora/blob/ec61ac5c905fd3df5e7391502b94556f5b12fff2/softwerkskammer/lib/activities/activity.js#L88

Ich schau die Tage mal. Bis dahin einfach deutsch arbeiten. :)

**Comment by caichinger** [comment]
Anscheinend gibt immer was zu tun. :)

Deutsch hat wunderbar geklappt, danke für die schnelle Info.

**Comment by leider** [comment]
please review and close

**Comment by caichinger** [comment]
Klappt, danke.

Was mir im Zuge des Ausprobierens aufgeallen ist, man kann vergangene Events (Event Datum vor dem heutigen) nicht löschen.

**Comment by leider** [comment]
another language problem - geht auf deutsch - bin verwundert, was die Sprach hier zu tun hat...

**Comment by leider** [comment]
Was genau geht beim Löschen nicht? UI oder Aktion oder sonst was? - Wenn der Button fehlt, hast Du einfach keine Rechte...

**Comment by caichinger** [comment]
Habe in #1443 ein Beispiel gebracht. Der Löschen Button wird nicht angezeigt. Mit der Sprache hat das nichts zu tun.
