### ISSUE TITLE
Unklarheit beim Löschen vergangener Aktivitäten

### ISSUE THREAD

**Issue by caichinger** [softwerkskammer/Agora#1443]
Ich erstelle eine Aktivität die in der Vergangenheit liegt und kann diese dann nicht löschen, weil der Button nicht aufscheint:

![image](https://user-images.githubusercontent.com/16005912/124379080-2c93b100-dcb5-11eb-9275-14af9becd164.png)

Ändere ich das Datum so, dass es in der Zukunft liegt, wird der Button angezeigt:

![image](https://user-images.githubusercontent.com/16005912/124379100-48975280-dcb5-11eb-8122-f661df9141f3.png)

---

Vielleicht ist das Verhalten so gewünscht, ich weiß es nicht. Mich hat es überrascht.

Das Verhalten ist unabhängig von der gewählten Sprache.

**Comment by leider** [comment]
Ja, das ist ein Feature: https://github.com/softwerkskammer/Agora/blob/e9c1984f83f2044c77593eec652f990936c8a5b8/softwerkskammer/lib/middleware/accessrights.js#L38
