### ISSUE TITLE
update.sh installs dev dependencies during the deployment

### ISSUE THREAD

**Issue by chr1shaefn3r** [softwerkskammer/Agora#1470]
`update.sh` executes `npm ci` and therefore installs all dependencies including the dev dependencies, which are not needed (hopefully) in the production deployment.
Suggestion would be to use `npm ci --production` to preven this.

**Comment by leider** [comment]
What is the benefit-cost ratio? 😀 

Seriously: sounds sensible. Maybe you can give it a try locally and report your findings?
