### ISSUE TITLE
Calendar export does not work any more?

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#1479]
My calendar does not show the activities of the imported group Karlsruhe - instead there is an exclamation mark next to the calendar in the calendars list:

<img width="168" alt="image" src="https://user-images.githubusercontent.com/436499/183716037-34a14294-7202-485f-995b-730ecd4d84eb.png">

Imported calendar URL: webcal://www.softwerkskammer.org/activities/icalForGroup/karlsruhe

Thanks for checking!

**Comment by leider** [comment]
Can confirm. It's a left-over bug of the previous ,migration to async/await. Will fix asap
