### ISSUE TITLE
Link zum Bearbeiten der Gruppenzugehörigkeit in versendeten E-Mails hinzufügen

### ISSUE THREAD

**Issue by UrsMetz** [softwerkskammer/Agora#1495]
In letzter Zeit gab es häufiger Antworten auf Einladungsmails, die darum baten "von der Mailingliste genommen" zu werden (u.a. auch mit dem Verweis auf potentielle rechtliche Folgen).

Daher kam @chr1shaefn3r, @pfichtner und mir die Idee, dass wir einfach in jede Mail einen Link auf die Profilseite (oder ähnliches) aufnehmen mit dem Hinweis, dass man sich dort austragen kann.

Falls diese Lösung gewünscht ist, kann ich einen PR mit entsprechenden Änderungen vorbereiten.

**Comment by leider** [comment]
Passt für michAm 13.06.2023 um 22:47 schrieb Urs Metz ***@***.***>:﻿
In letzter Zeit gab es häufiger Antworten auf Einladungsmails, die darum baten "von der Mailingliste genommen" zu werden (u.a. auch mit dem Verweis auf potentielle rechtliche Folgen).
Daher kam @chr1shaefn3r, @pfichtner und mir die Idee, dass wir einfach in jede Mail einen Link auf die Profilseite (oder ähnliches) aufnehmen mit dem Hinweis, dass man sich dort austragen kann.
Falls diese Lösung gewünscht ist, kann ich einen PR mit entsprechenden Änderungen vorbereiten.
