### ISSUE TITLE
Fehler beim "Austreten"

### ISSUE THREAD

**Issue by pfichtner** [softwerkskammer/Agora#1497]
Ein Benutzer welcher austreten möchte erhält folgende Fehlermeldung. 
Mehr ist mir leider auch nicht bekannt bzw. müsste man dann gezielt rückfragen. 

![grafik](https://github.com/softwerkskammer/Agora/assets/1958485/d74ef6a9-ac34-4ec4-85ad-ec196a1ea102)

**Comment by leider** [comment]
Der user ist nicht bekannt?

**Comment by leider** [comment]
Voreilig. Kann reproduzieren. Accepted as bug

**Comment by leider** [comment]
FIXED

**Comment by pfichtner** [comment]
> Der user ist nicht bekannt?

@leider User nicht, aber Mailadresse. Hilft das? Dann schicke ich sie Dir per PM

**Comment by leider** [comment]
Er soll einfach nochmal. Ist gefixt. Am 19.06.2023 um 21:07 schrieb Peter Fichtner ***@***.***>:﻿

Der user ist nicht bekannt?

@leider User nicht, aber Mailadresse. Hilft das? Dann schicke ich sie Dir per PM

**Comment by leider** [comment]
Nein, jetzt nicht mehr
