### ISSUE TITLE
Parsen/Anfragen für Announcements analog zu Activities reparieren

### ISSUE THREAD

**Issue by marcphilipp** [softwerkskammer/Agora#344]
Sobald #329 durch ist, sollte man sich mal die Announcements genauer anschauen. Dort müsste es das gleiche Problem geben.

**Comment by leider** [comment]
Ich würde lieber die Announcements komplett entfernen. Das Feature wird nicht genutzt und anscheinend auch nicht nachgefragt.

**Comment by NicoleRauch** [comment]
Ich halte das Entfernen der Announcements auch für eine gute Idee im Sinne der Codesauberkeit und -klarheit.

**Comment by leider** [comment]
I'll do that

**Comment by leider** [comment]
will be done via PR
