### ISSUE TITLE
Blog-Anzeige kommt nicht mit jedem Markdown zurecht

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#643]
Wird die Überschrift eines Blog-Artikels nicht mit vorangestellten Hashes (#) formatiert, sondern mit nachfolgender Unterstreichung (=====), zeigt die Blog-Preview nicht mehr den ersten Textabschnitt an.

**Comment by leider** [comment]
keine Relevanz mehr
