### ISSUE TITLE
Löschen von Inhalten in Session Snap

### ISSUE THREAD

**Issue by drosowski** [softwerkskammer/Agora#807]
Ich habe mein Session Flipchart versehentlich mehrfach hochgeladen. Einmal unter #Everywhere und einmal unter #Köln. Bisher konnte ich noch nicht herausfinden wie ich den falschen Eintrag unter Everywhere löschen kann.

**Comment by NicoleRauch** [comment]
Funktioniert jetzt. (Magie!)
