### ISSUE TITLE
OpenID-Einträge löschen

### ISSUE THREAD

**Issue by softmetz** [softwerkskammer/Agora#825]
Es ist möglich weitere Authentifizierungs-Provider anzulegen, man kann aber diese nicht mehr löschen.

**Comment by NicoleRauch** [comment]
Hey @softmetz ,

gibt es hier noch Handlungsbedarf? Wenn ja, melde Dich bitte nochmal. Wenn nein, den Issue bitte schließen.

Danke,
Nicole

**Comment by softmetz** [comment]
Hallo @NicoleRauch,

die Funktion macht sicher noch sinn, mein Problem besteht nicht mehr.

Viele Grüße
Christian
