### ISSUE TITLE
OpenID-Delegationen werden mit echtem Provider gecached

### ISSUE THREAD

**Issue by softmetz** [softwerkskammer/Agora#826]
Offenbar funktionieren OpenID-Delegationen nicht richtig. Ich habe mich mit einer Delegation zu einem Zeitpunkt angemeldet, als diese auf Google zeigte. Zwischenzeitlich wird der Aufruf (eigentlich) an einen anderen Provider weitergeleitet.

Melde ich mich auf softwerkskammer.de mit der id an, bekomme ich nur eine Fehlermeldung von Google, die alte Provider-URL scheint also gecached zu werden was aber den Sinn von OpenID-Delegationen ad absurdum führt.

**Comment by NicoleRauch** [comment]
Hey @softmetz ,

gibt es hier noch Handlungsbedarf? Wenn ja, melde Dich bitte nochmal. Wenn nein, den Issue bitte schließen.

Danke,
Nicole

**Comment by softmetz** [comment]
**Workaround:** Der Parser kann kann mit OpenID-Meta-Tags in Kommentaren nicht umgehen, sofern man diese aus der HTML-Datei löscht, klappt es.
