### ISSUE TITLE
Some of group emails are not listed in archive

### ISSUE THREAD

**Issue by vinogradoff** [softwerkskammer/Agora#838]
1. go to https://www.softwerkskammer.org/mailarchive/list/threaded/freelance-topics

Expected: every mail is shown
Actual: at the moment emails up to 22.10 are shown, a bunch emails last-week until today is not in the list.

**Comment by NicoleRauch** [comment]
Jetzt sollten alle eMails wieder im Archiv sein - bitte mal prüfen und Issue schließen oder fehlende Mails (Datum!) angeben, dann importiere ich nochmal.
