### ISSUE TITLE
Inkonsistenzen bei Anmeldungen zu Aktivitäten

### ISSUE THREAD

**Issue by dpolivaev** [softwerkskammer/Agora#887]
Auf dem letzten Treffen hatten wir über 40 Leute und mussten deswegen Wartelisten verwenden. Um eine einzige Warteliste zu haben nehmen wir Anmeldungen zu unseren Events ab jetzt über http://www.meetup.com/Software-Craftsmanship-Meetup-Softwerkskammer-Munchen  - genau diese Seite hat wesentlich dazu geführt, dass so viele Leute gekommen sind. 

Also wollte ich für das nächste Event die Anmeldung nur über die genannte Seite ermöglichen, und keine Anmeldungen über die Softwerkskammer mehr zulassen.

Irgendwie habe ich das geschafft indem ich "Anzahl" auf der Resourcenseite auf "0" setzte. Dann wurde Text "Anmeldung ist nicht über die Softwerkskammer möglich." angezeigt und der Anmeldeknopf war weg.

Leider gibt es dabei noch folgende Inkonsistenzen:

1. Es wird weiterhin Text "Bislang gibt es keine Teilnahmezusagen." angezeigt. Aus meiner Sicht ist dieser Text in dem Sinne falsch, dass die Teilnahmezusagen bei dieser Konfiguration über diese Seite gar nicht erfolgen können.

2. Wenn ich die Einladungen verschicke, beinhalten sie den "Count me - Ich bin dabei!" Knopf, obwohl der Link dahinter nicht zu einer Enmeldung führt. Ich glaube, dass für Veranstaltungen, wo Anmeldung nicht aktiv ist, auch dieser Knopf nicht in die Mails gehören sollte.

Grüße,
Dimitry

**Comment by leider** [comment]
Ja, da hast du recht. Sogar 2x

**Comment by dpolivaev** [comment]
Danke.
Was ich zunächst nicht geschrieben habe, ich finde es nicht ganz intuitiv, dass man Spalte "Anzahl" in Reihe "Veranstaltung" auf 0 setzen muss, um zu bewirken, dass die Anmeldungen deaktiviert werden. Aus meiner Sicht wäre es intuitiver, wenn die Reihe "Anmeldungen" oder "Teilnehmer" heißen könnte.

**Comment by leider** [comment]
Unintuitiv ist es immer noch, aber der Anmeldebutton ist jetzt generell aus den Mails draussen. Ist das OK für Dich? - Wenn ja, bitte schliessen.

**Comment by NicoleRauch** [comment]
Der Text, den Du in Punkt 1 kritisiert hast, ist geändert, und wie Andreas schon geschrieben hat, ist der Anmeldebutton nicht mehr in der Mail drin.

Du kannst die Reihe übrigens selbst umbenennen, wenn Dir das besser gefällt; "Veranstaltung" ist nur ein Vorschlag.
