### ISSUE TITLE
Warteliste wird ignoriert, wenn sich Teilnehmer abmelden

### ISSUE THREAD

**Issue by dpolivaev** [softwerkskammer/Agora#888]
Wenn Teilnehmerliste voll ist und einige Leute auf der Warteliste stehen, dann erwarte ich, dass die automatisch in der Reihenfolge der Einträge in die Teilnehmerliste übernommen werden, wenn sich bestätigte Teilnehmer abmelden. Nun habe ich die Erfahrung gemacht, dass es nicht so passiert, und die Abmeldungen keine Auswirkungen auf die Warteliste haben.

**Comment by leider** [comment]
Das ist Absicht. Die Warteliste muss aktiv gemanagt werden. 

Bei bisherigen Events mit Warteliste war das sehr praktisch. L

**Comment by dpolivaev** [comment]
Als Organisator möchte ich die Option haben, die Warteliste automatisch ablaufen zu lassen. Es ist einfach und es ist fair.

Momentan muss ich immer wenn einer abspringt genau einen Teilnehmer von der Warteliste informieren, dass er sich neu anmelden muss, und ihm noch eine Frist setzen. => IMHO nicht praktikabel.

**Comment by dpolivaev** [comment]
Und dazu besteht immer das Risiko, dass sich jemand neu anmeldet, der gar nicht auf der Warteliste steht und nur das Glück hat. Damit erfüllt Warteliste ihre Funktion nicht.

**Comment by NicoleRauch** [comment]
Zu 1) Wenn es automatisch geschieht, rutscht vielleicht einer nach, der dann doch nicht kommt, weil er es gar nicht so ernst gemeint hat -> ist Dir das lieber?

Zu 2) Sobald die Warteliste aktiviert wird, sollte eigentlich automatisch die direkte Anmeldung deaktiviert werden, d. h. es kann sich niemand mehr direkt anmelden. Wenn das nicht so ist, dann ist das ein Bug -> kannst Du das dann bitte gesondert erfassen?

**Comment by dpolivaev** [comment]
Zu 1) Wie kann ich generell beurteilen ob eine Anmeldung bzw. Wartelistenplatz ernst gemeint sind? Bei den regulären Anmeldungen hinterfrage ich es auch nicht. Statt dessen verschicke ich vor der Veranstaltung eine Mail mit der Bitte dass sich die Leute  abmelden, die nicht kommen können, wenn wir andere Leute auf der Warteliste haben. 

Auf Englisch:  
> Hi,
> as we already have a Waitlist for the Software Craftsmanship Meetup on Thursday the 15th, I'm > kindly asking all of you to double check if you can attend and unregister if this has changed.
> See you!

Auf Deutsch:

> Hallo,
> da wie wir bereits eine Warteliste für das Treffen am kommenden Donnertag haben, möchte ich > Euch bitten, zu überprüfen, ob Ihr kommen könnt, und Euch abzumelden, falls es nicht mehr 
> möglich ist.
> Bis dann!

**Comment by dpolivaev** [comment]
Zu 2) Ich habe eine Testaktivität angelegt. Leider habe ich kein 2. Konto und kann das Spiel deswegen nicht alleine durchspielen
Kannst Du Dich bitte in https://www.softwerkskammer.org/activities/wartelistentest auf die Warteliste setzen?

**Comment by dpolivaev** [comment]
Dann würde ich mich abmelden und wir können schauen, ob ich mich dann wieder anmelden kann (Bug) oder nicht.

**Comment by NicoleRauch** [comment]
Bin auf der Warteliste, der Test kann losgehen :-)

**Comment by NicoleRauch** [comment]
Zu 1) "Wie kann ich generell beurteilen ob eine Anmeldung bzw. Wartelistenplatz ernst gemeint sind?"

Um das für einen Wartelistenplatz beurteilen zu können, haben wir die Rückfrage mit Fristsetzung eingebaut...

**Comment by NicoleRauch** [comment]
OK, kein Bug: "Anmeldung ist zur Zeit nicht möglich."

**Comment by dpolivaev** [comment]
OK, kein Bug. Ich nehme an, ich habe die Anmeldung selber auf "möglich" geschaltet, als ich mich wunderte, dass Leute nicht nachrücken.

**Comment by dpolivaev** [comment]
Zu 1): die automatisch funktionierende Warteliste wie auf Meetup, die ich beschreibe, hat genau so einen Sinn, wie die Agora-Warteliste mit der manuellen Steuerung. Und sie gibt es ja bereits auf Meetup. Insofern ist der Wunsch, auch bei Agora das automatische Nachrücken Warteliste zu ermöglichen, für mich persönlich nicht sehr wichtig. Ihr könnt es Euch trotzdem überlegen. Wenn es sonst keiner braucht, schließe einfach diesen Request.

Danke für das "Gespräch"

**Comment by NicoleRauch** [comment]
OK, danke für den Hinweis! Wir werden sowieso in den nächsten Monaten die Aktivitäten wieder etwas "entschlacken" (weil der SoCraTes-Code in eine eigene Applikation verlagert wird), dann werden wir uns Deinen Vorschlag nochmal durch den Kopf gehen lassen. Bis dahin schließe ich diesen Request.

Dir auch danke für das "Gespräch" :-)
