### ISSUE TITLE
Login to an existing account via Google OpenID asks to create a profile

### ISSUE THREAD

**Issue by linkclau** [softwerkskammer/Agora#894]
Wenn I try to login at http://www.socrates-conference.de/ through Google as OpenID provider I get redirected to the registration page.
There I can't register because my email address is already registered (yes I should have an account).

AFAIK my account is connected through my Google OpenId.
My authentication (through Google OpenId) on https://www.softwerkskammer.org works

Oh, it gets even funnier. If I do login on http://www.socrates-conference.de/history.html it works %-/

**Comment by leider** [comment]
Manuelle URL Eingabe? Oder der Google Button?

**Comment by NicoleRauch** [comment]
This is indeed a bug! To fix it, please log in to Softwerkskammer first, then your login into SoCraTes works again.

Working on it...

**Comment by NicoleRauch** [comment]
Der Bug sollte jetzt gefixt sein. 

@linkclau: Wenn Du mal Zeit hast, melde Dich doch mal bitte bei mir, ich würde ihn gern gemeinsam mit Dir verifizieren.

**Comment by NicoleRauch** [comment]
Der Bug (es war tatsächlich einer!) ist jetzt gefixt, daher schließe ich diesen Issue.

@linkclau: Wenn Du den Bug nochmal verifizieren möchtest, melde Dich doch einfach bei mir. Ich kann Deine SoCraTes-Anmeldung zu Testzwecken zurücknehmen.
