### ISSUE TITLE
List upcoming (past) events in group page

### ISSUE THREAD

**Issue by danbim** [softwerkskammer/Agora#897]
It would be great to have a listing of upcoming and past activities in the group page. Currently you'd have to manually filter the activities of your local group out of all activities while IMHO the natural workflow is to browse to your local group first to see what's up next near you.

**Comment by NicoleRauch** [comment]
Good point! Where would you preferably put this information? On top of the members, underneath the group description? Or do you see any better place for it?

**Comment by NicoleRauch** [comment]
@danbim Can you give me a bit more input please? Otherwise I'll close this issue.

**Comment by danbim** [comment]
Sorry, and yes, on top of the member list is just a perfect place IMO.

**Comment by leider** [comment]
Danke, das hilft. 

Geht's ein wenig genauer? :)
Eine Skizze wäre hilfreich. - Natürlich reicht auch ein Pull Request. :)

Kann ich dir bei so etwas helfen?

Gruß
Andreas

**Comment by danbim** [comment]
Hmm, spontan würde ich die gleiche Darstellung nehmen die auch die "Teilgenommen an" - Liste auf der User-Profil-Seite hat, z.B. https://www.softwerkskammer.org/members/danbim. Nur natürlich dass sie vor allem die zukünftigen (oder auch die früheren) Treffen anzeigt. Das wäre doch schon ein schöner Anfang. Vielleicht kann man da ja auch Code wiederverwenden?!

Würde das gerne auch selbst machen, hab nur gerade nicht die Luft dafür...

Grüße
Daniel

**Comment by NicoleRauch** [comment]
Also das mit den zukünftigen Treffen kaufe ich sofort :-)

Das mit den vergangenen kann ich mir noch nicht so ganz vorstellen... Insbesondere mit dem Wissen, dass z. B. die Karlsruher Gruppe schon über 50 Treffen hat, von denen bestimmt 30 auf dieser Plattform gelaufen sind... Klingt für mich eher, als würde das auch ein ziemliches Datengrab.

Fragen: 
* Braucht man die Liste der vergangenen Treffen wirklich? 
* Braucht man sie auf der Gruppenseite? (Andere Mechanismen, wie ein Filter auf der allgemeinen Aktivitäten-Listen-Seite, wären ja auch denkbar.) 
* Wenn man sie auf der Gruppenseite braucht, wie soll das dargestellt werden? (Ich könnte mir z. B. was zum Ausklappen vorstellen. Die platte Liste vergangener Aktivitäten kann ich mir auf der Gruppenseite nicht vorstellen.)

**Comment by danbim** [comment]
> On 17 Feb 2015, at 11:00, Nicole Rauch <notifications@github.com> wrote:
> 
> Also das mit den zukünftigen Treffen kaufe ich sofort :-)
> 
> Das mit den vergangenen kann ich mir noch nicht so ganz vorstellen... Insbesondere mit dem Wissen, dass z. B. die Karlsruher Gruppe schon über 50 Treffen hat, von denen bestimmt 30 auf dieser Plattform gelaufen sind... Klingt für mich eher, als würde das auch ein ziemliches Datengrab.

Ja, prinzipiell gebe ich dir da recht. Wenn man es macht bräuchte man da schon eine relativ aufwändig zu implementierende View mit paging etc. sonst ist das einfach nur unübersichtlich und störend.

> 
> Fragen:
> 
> 	• Braucht man die Liste der vergangenen Treffen wirklich?

Der einzige Use Case der mir spontan einfällt (den ich aber auch nicht komplett unwichtig finde): wenn ich die Gruppenseite zum Ersten Mal besuche und die Softwerkskammer noch nicht kenne gibt mir diese Liste die Möglichkeit rauszufinden was in der Gruppe so geht. Welche Themen werden/wurden (schon) besprochen? Daraus kann ich natürlich ableiten wie die Gruppe so tickt und was die Zukunft bringen könnte / bzw. was ich selbst beitragen könnte und ob ich da rein passe.

Inwiefern das jemanden motiviert der Gruppe beizutreten und zu den Treffen zu gehen ist natürlich eine ganz andere Frage… 

Ich würde ich das Feature definitiv nicht von der Liste möglicher Weiterentwicklungen streichen aber es niedrig priorisieren.

> 	• Braucht man sie auf der Gruppenseite? (Andere Mechanismen, wie ein Filter auf der allgemeinen Aktivitäten-Listen-Seite, wären ja auch denkbar.)

Wenn man an den Use Case denkt den ich gerade beschrieben habe, ja.

Spontanes Ideen-Auskotzen: wenn man über die Implementierung nachdenkt würde ich (ohne bisher zu wissen wie der Code aufgebaut ist) dazu tendieren ein Widget zu schreiben was man an verschiedenen Stellen der Seite integrieren kann. Dieses könnte dann z.B. wie Du vorschlägst

 * einen durch die GUI manuell konfigurierbaren Filter haben (für die allgemeinen Aktivitäten-Liste)
 * im Falle der Gruppenseite einen im Code vordefinierten Filter (und keine GUI-Element zum Verändern) der den Ort filtert und
 * im Falle der User-Profil-Seiten ebenfalls einen vordefinierten Filter der Events anzeigt die der User besucht hat.

Am Ende schlagen halt verschiedene Queries im Backend ein, was aber gleich ist wäre das Widget zum Darstellen der Treffen.

> 	• Wenn man sie auf der Gruppenseite braucht, wie soll das dargestellt werden? (Ich könnte mir z. B. was zum Ausklappen vorstellen. Die platte Liste vergangener Aktivitäten kann ich mir auf der Gruppenseite nicht vorstellen.)

Wie gesagt, zukünftige Treffen priorisieren, frühere funktionieren natürlich nur mit Paging. Ansonsten würde ich mir spontan Tabs zum Umschalten zwischen zukünftigen und früheren denken.

**Comment by NicoleRauch** [comment]
> > • Braucht man die Liste der vergangenen Treffen wirklich?
> 
> Der einzige Use Case der mir spontan einfällt (den ich aber auch nicht komplett unwichtig finde): wenn ich die Gruppenseite zum Ersten Mal besuche und die Softwerkskammer noch nicht kenne gibt mir diese Liste die Möglichkeit rauszufinden was in der Gruppe so geht. Welche Themen werden/wurden (schon) besprochen? Daraus kann ich natürlich ableiten wie die Gruppe so tickt und was die Zukunft bringen könnte / bzw. was ich selbst beitragen könnte und ob ich da rein passe.

Sowas in der Art ist auch das einzige, was mir eingefallen ist.

> > • Braucht man sie auf der Gruppenseite? (Andere Mechanismen, wie ein Filter auf der allgemeinen Aktivitäten-Listen-Seite, wären ja auch denkbar.)
> 
> Wenn man an den Use Case denkt den ich gerade beschrieben habe, ja.

Guter Punkt.

> Spontanes Ideen-Auskotzen: wenn man über die Implementierung nachdenkt würde ich (ohne bisher zu wissen wie der Code aufgebaut ist) dazu tendieren ein Widget zu schreiben was man an verschiedenen Stellen der Seite integrieren kann.

Danke für Deine Vorschläge! Grundsätzlich stimme ich Dir zu. Allerdings ist es bei uns so, dass wir keine Frontend-Logik haben, sondern dass alles im Backend gerendert wird. Aber das ändert natürlich nichts am ganz allgemeinen Prinzip der Wiederverwendung einzelner Darstellungsbereiche ;-)

OK, dann halte ich mal fest: Zukünftige Treffen bald, vergangene Treffen irgendwann mal und nur mit geeigneter Darstellung.

Danke!

**Comment by leider** [comment]
Zukünftige sind umgesetzt. Bitte mal schauen, ob das so passt.

**Comment by danbim** [comment]
Sieht super aus! Danke!

**Comment by NicoleRauch** [comment]
Den Teil mit den vergangenen Aktivitäten hab ich mal in unser Backlog verschoben:

https://github.com/softwerkskammer/Agora-Backlog/issues/148

und schließe damit diesen Issue.
