### ISSUE TITLE
Aktivitäts-Hover im Kalender erscheint rechts vom Kalender

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#905]
... wenn die Activity von Montag bis Sonntag dauert.

**Comment by leider** [comment]
Screenshot

**Comment by NicoleRauch** [comment]
![bildschirmfoto 2015-02-14 um 18 57 57](https://cloud.githubusercontent.com/assets/436499/6200507/a0cf52fe-b47b-11e4-80e8-0f3db2f1cdae.png)

**Comment by NicoleRauch** [comment]
Besonders lustig: Man kann dann weiter nach rechts scrollen als sonst!

![bildschirmfoto 2015-02-14 um 18 59 20](https://cloud.githubusercontent.com/assets/436499/6200510/af972000-b47b-11e4-8355-7ecd6f97e3ed.png)

**Comment by NicoleRauch** [comment]
Passiert interessanterweise nicht immer, bei einer anderen langandauernden Activity erscheint der Hover links vom Balken.

**Comment by NicoleRauch** [comment]
Ist wohl unvermeidlich - und wir haben auch nur selten so lang dauernde Aktivitäten.
