### ISSUE TITLE
Relative Links von Aktivitäten zu Wiki - Seiten werden in den Einladungsmails falsch dargestellt

### ISSUE THREAD

**Issue by dpolivaev** [softwerkskammer/Agora#910]
Aktivitätenbeschreibung https://www.softwerkskammer.org/activities/28._Treffen_der_Softwerkskammer_Muenchen verweist auf Wiki-Seite https://www.softwerkskammer.org/wiki/muenchen/themen-und-moderatoren mit dem Markdown-Fragment `Diese Vorschläge sind kurz auf unserer [Themenseite in Wiki](/wiki/muenchen/themen-und-moderatoren) beschrieben.` Dieser Link funktioniert auf der Seite selbst gut. In der automatisch generierten Mail mit der Einladung wird er im HTML - Abschnitt nur als `<p>Diese Vorschl=C3=A4ge sind kurz auf unserer <a href=3D"/wiki/muenchen/themen-und-moderatoren">Themenseite in Wiki</a> beschrieben.</p>` dargestellt, und dieser Link aus der Mail geht nicht.

Es wäre also wünschenswert, bei der Generierung von Mails aus den Seiteninhalten alle URLs als absolute URLs darzustellen.

**Comment by leider** [comment]
Du hast absolut recht. Über einen PR zu dem Thema freuen wir uns.

Bis dahin funktioniert der Workaround, die Links absolut zu erstellen. *sorry*

**Comment by dpolivaev** [comment]
Ich hab node in Vagrant leider nicht zum laufen gekriegt, https://github.com/softwerkskammer/Agora/issues/924

**Comment by NicoleRauch** [comment]
Hallo @dpolivaev - bitte mal prüfen und ggf. schließen. Danke!
