### ISSUE TITLE
Auf der Seite einer Regionalgruppe nur Termine der Gruppe im Kalender anzeigen

### ISSUE THREAD

**Issue by danbim** [softwerkskammer/Agora#915]
Vielleicht ist es ja so gewollt aber ich finde es verwirrend wenn man bei Besuch der Seite einer Regionalgruppe rechts im Kalender alle Termine aller Regionalgruppen angezeigt bekommt, statt nur die Termine dieser Gruppe. Das sieht dann zwar etwas leer(er) aus, passt aber besser zum Kontext in dem man gerade ist.

**Comment by leider** [comment]
Es gibt ein "hidden" feature Dashboard. Das macht eine quasi personalisierte Sicht.

https://www.softwerkskammer.org/dashboard/

Wäre das damit erledigt? - Also, wenn das Feature mal rund ist.

**Comment by danbim** [comment]
Nein, eher nicht. Das Dashboard ist zwar sicherlich praktisch in der Beziehung aber es geht tatsächlich um die Gruppenseite, also z.B. https://www.softwerkskammer.org/groups/luebeck. Da finde ich es einfach verwirrend wenn ich da die Termine von z.B. Karlsruhe sehe. IMHO sollte der Kalender rechts eigentlich nur eine grafische Version der "Kommende Aktivitäten" links auf der Gruppenseite sein.

Wenn man allerdings so drüber nachdenkt ist das dann auch doppelt gemoppelt also könnte der Kalender genauso gut raus und für was anderes Platz machen... Man könnte genauso gut auch "Kommende Aktivitäten" an Stelle des Kalenders haben.

**Comment by sparsick** [comment]
Wir hatte heute in unsere Gruppe die Diskussion über die Struktur der Regionalgruppenseite. Wir finden es auch unglücklich, dass die "Kommenden Aktivitäten" weit unten aufgelistet werden. In der Diskussion wurde vorgeschlagen, dass die "Kommenden Aktivitäten" oberhalb der Word Cloud aufgelistet werden. Ich finde, dass ist ein Kompromiss.

**Comment by NicoleRauch** [comment]
Habt Ihr in Eurer Gruppe vielleicht Lust, daran zu arbeiten? Das könnte ja zum Beispiel Thema eines Treffens sein ;-)
Veränderungen des Layouts sind nicht wirklich schwierig, wenn man Jade ein bisschen kennt. Und unter Linux oder Mac OS lässt sich die Software auch normalerweise leicht zum Laufen bringen.

**Comment by sparsick** [comment]
Heute Abend haben wir wieder ein Treffen. Ich werde da mal abklopfen wie das generelle Interesse da ist. Für das konkrete Problem habe ich mal selber mit Jade experimentiert und meinen Vorschlag implementiert. Pull request ist erstellt.

**Comment by NicoleRauch** [comment]
Ich habe das neue Feature mal deployed, schaut es Euch mal an, ob das so besser ist. (Sorry, ich hab's gestern leider nicht mehr geschafft, sonst hättet Ihr es gleich bei Eurem Treffen anschauen können.)

Ich persönlich hätte glaube ich lieber keine Lücke zwischen dem Beschreibungstext und der Mitgliederliste (siehe z. B. die Gruppe Karlsruhe).

**Comment by sparsick** [comment]
Danke für das Deployment! 

Ja, die Lücke zwischen Beschreibungstext und Mitgliederliste ist unschön. Ich werde mal am Wochenende versuchen eine Lösung zu finden, um diese Lücke zu schließen.

**Comment by sparsick** [comment]
Ich habe eine mögliche Lösung implementiert, um die Lücke zwischen Beschreibungstext und Mitgliederliste zu schließen. 

Ist es möglich sich über die OpenId Provider in der lokalen deployten Platform anzumelden? Ich habe es mal versucht und bekomme nur eine 404 Seite angezeigt.

**Comment by NicoleRauch** [comment]
Bei Google und Github ist das nicht so einfach... (man muss seine App dort registrieren). StackExchange weiß ich gerade nicht auswendig, könnte funktionieren. Ansonsten mach Dir einfach einen Account bei xlogon.net und trag das in die Textbox ein (alternative Provider oder so). HTH!

**Comment by sparsick** [comment]
Danke für den Hinweis. Das wird das Testen um einiges vereinfachen.

**Comment by leider** [comment]
Ist hier noch was offen?

**Comment by sparsick** [comment]
Aus meiner Sicht nicht. Was meinst du @danbim ?

**Comment by NicoleRauch** [comment]
Sieht nicht so aus...
