### ISSUE TITLE
Vagrant does not initialize properly

### ISSUE THREAD

**Issue by dpolivaev** [softwerkskammer/Agora#924]
```
vagrant@vagrant:/vagrant$ npm install
...

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/npm-debug.log
npm ERR! not ok code 0

`vagrant@vagrant:/vagrant$ node softwerkskammer/initialDBSetup

module.js:340
    throw err;
          ^
Error: Cannot find module 'mongodb'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.persistence.openDB (/vagrant/softwerkskammer/lib/persistence/persistence.js:171:25)
    at new module.exports (/vagrant/softwerkskammer/lib/persistence/persistence.js:201:15)
    at eval (eval at <anonymous> (/vagrant/node_modules/CoolBeans/lib/CoolBeans.js:111:10), <anonymous>:1:7)
    at get (/vagrant/node_modules/CoolBeans/lib/CoolBeans.js:111:5)
    at Object.<anonymous> (/vagrant/softwerkskammer/initialDBSetup.js:5:32)
    at Module._compile (module.js:456:26)
vagrant@vagrant:/vagrant$

vagrant@vagrant:/vagrant$ npm test

> Agora@1.0.0 test /vagrant
> grunt tests && grunt --gruntfile Gruntfile-SoCraTes.js tests

grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
npm ERR! weird error 99
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

**Comment by sparsick** [comment]
Mit dem aktuellen Stand lief das Aufsetzen von Agora bei mir durch. 

Mein Setup ist
OS Linux Mint 17.1 64Bit
Vagrant 1.7.2
Virtualbox 4.3.26

**Comment by leider** [comment]
Hallo @dpolivaev 

kannst Du das verifizieren oder einfach als "nicht so wichtig" beurteilen. In diesen Fällen bitte schliessen. Falls es bei Dir immer noch nicht klappt, sollten wir versuchen, rauszufinden, warum.

**Comment by dpolivaev** [comment]
Hallo Andreas, 

ich habe mir nun das Problem genauer angeschaut, und es kommt daher dass node_modules in Projektverzeichnis liegt, der mit Windows als shared folder geteilt werden muss. Und es führt zu verschiedenen Schwierigkeiten:

1. Es können keine Links in der VM erzeugt werden. Dieses Problem ist in https://github.com/npm/npm/issues/2380 diskutiert.

2. Die Pfadnamen sind für Windows und VirtualBox zu lang.

3. Wenn ich unter vagrant VM den inhalt aus /vagrant in einen nicht geteilten Folder kopiere läuft npm install durch, es kommt nachher noch zu Fehlern in npm test, die ich nicht weiter analysiert habe.

4. Und mein Versuch statt Verzeichnisse unter VirtualBox zu teilen, sie mit rsync zu synchronisieren, beschrieben unter https://docs.vagrantup.com/v2/synced-folders/rsync.html , hat auch nicht funktioniert da rsync scheiterte.

Fazit: Vagrant unter Windows geht nicht

**Comment by leider** [comment]
Das ist zwar schade aber jetzt wissen wir mehr. Vielen Dank!

**Comment by NicoleRauch** [comment]
@dpolivaev: Ist hier noch etwas offen? Wenn ja, kannst Du das bitte nochmal kurz beschreiben? Ansonsten schließen. Danke!
