### ISSUE TITLE
Kann mich nicht (mehr) anmelden

### ISSUE THREAD

**Issue by hwheinzen** [softwerkskammer/Agora#925]
Hallo,

am 2.2.15 16:35 habe ich mich bei der Softwerkskammer und für die Gruppe Nürnberg registriert, authentifiziert über mein Google-Konto hwheinzen@bitloeffel.de. Ein paar Tage lang konnte ich mich dann auch anmelden. Doch bald darauf (?wann genau?) nicht mehr.
A) Auf der Seite der Softwerkskammer starte ich nun immer als "Gast", egal ob ich bei Google angemeldet bin oder nicht. (Anmelden für Google Groups funktioniert nach wie vor.)
B)Wenn ich dann versuche mich anzumelden, wähle ich im Fenster "Authentifizierung" die Taste "g+Google", gebe im Google-Anmeldedialog Benutzer+Kennwort (oder auch nur das Kennwort) ein, und lande dann *nicht* bei der Softwerkskammer, sondern jedesmal bei Google Kontoeinstellungen, und von hier gibt's kein vor und kein zurück.
C) Versuchsweise hatte ich sogar schon ein Google+-Konto angelegt. Geholfen hat's nicht, also hab ich's wieder gelöscht.

Was mach ich falsch? Woran kann's liegen?
(Kann es sein, dass am 2.2. die Authentifizierungstaste noch "Google" und nicht "g+Google" hieß, und kann's damit zusammenhängen?)

Grüße
Hans-Werner Heinzen

**Comment by leider** [comment]
Hallo,

das sind ja viele Fragen auf einmal. :)

Zuerst die letzte: wir authentifizieren jetzt mit Googles neuer API gegen G+ und nicht mehr wie vorher direkt über OpenID

Dein Use Case ist kein Einzelfall (Google vorher), allerdings sind deine Probleme bislang unbekannt.

Probiere mal:
a) über github
b) wenn du in G+ angemeldet bist, solltest Du keinen G+ Anmeldedialog erhalten, sondern direkt wieder in der Softwerkskammer landen.

Bitte mach mal ein paar Screensshots (ggf. geschwärzt) und schau in die JavaScript Konsole

**Comment by leider** [comment]
probiere doch mal nen anderen Browser oder sogar nen anderen Computer. Deine Authentifizierung mit G+ ist bei uns sichtbar.

**Comment by hwheinzen** [comment]
Danke für die schnelle Antwort.
Ok, hab jetzt ein bisschen was ausprobiert.

Also, wenn ich über die Taste "Github" gehe, komme ich zum "Profil anlegen - SWK" für neue Mitglieder, aber das habe ich ja schon am 2.2. getan.

Browser: 
Normalerweise benutze ich Iceweasel (31.5.0). Dort gibt's die o.g. Probleme.
Konqueror geht gar nicht (Pull-down-Menu unter Gast geht gar nicht auf).
Webbrowser (3.4.2) - das scheint der von Gnome zu sein - hier geht's plötzlich!!!

Hm, das würde mir als Krücke erstmal reichen. Trotzdem stimmt da noch was nicht.

Google+: Dort möchte ich mich eigentlich nicht auch noch anmelden müssen. Und, wie schon gesagt, ich hatte einen Versuch gemacht, aber ohne positves Ergebnis.

JavaScript-Konsole? Ich glaub, da fehlt mir das Knowhow.

**Comment by leider** [comment]
Hallo,
schön, dass Du einen Workaround gefunden hast.

ist es einfach für uns, Dein Problem nachzustellen? - Evtl. mit einer VM unter vagrant o.ä.?

Das wäre super.

Wenn Dir das zu umständlich erscheint, würde ich Dich bitten, den Issue zu schliessen.

Gruß

**Comment by hwheinzen** [comment]
Keine Ahnung, ob das enfach wäre. Kenne vagrant nicht, und mit einer VM habe ich auch noch nicht gearbeitet ... Dann werde ich mal lieber diesen Punkt abschließen.
(Für den Fall, dass ihr doch noch weiter recherchieren möchtet: Debian Stable, Iceweasel 31.5.0 )
Grüße
