### ISSUE TITLE
Als Aufruf der Teilnehmerliste einer Aktivität erscheint eine 404 Seite

### ISSUE THREAD

**Issue by sparsick** [softwerkskammer/Agora#935]
Wenn ich als Anleger der Aktivität auf *Teilnehmer* klicke (Beispiel https://www.softwerkskammer.org/activities/addons/do-mai-2015), erscheint eine 404 Seite.

**Comment by leider** [comment]
Kannst Du ein bisschen ausführlicher beschreiben, was Du machst?

* Du legst eine Aktivität an
* Dann, ???

**Comment by NicoleRauch** [comment]
Oh, Problem erkannt! Da war ich wohl etwas zu gründlich beim Aufräumen... 

Sorry! Ich baue es wieder ein.

**Comment by sparsick** [comment]
:) Gerne! Die Schritte waren:
* Aktivität wurde angelegt.
* Einladung wurde verschickt.
* Teilnehmer haben sich angemeldet.
* Dann klicke ich als Anleger der Aktivität auf das Symbol *Teilnehmer*

**Comment by NicoleRauch** [comment]
Jetzt geht's wieder :-)

**Comment by sparsick** [comment]
Danke
