### ISSUE TITLE
"Back" auf SoCraTes Memberprofil-Edit gibt falsche Statusmeldung

### ISSUE THREAD

**Issue by NicoleRauch** [softwerkskammer/Agora#944]
Bearbeitet man sein Profil in der SoCraTes und klickt auf "Back", erscheint fälschlicherweise die Meldung

Saving Successful

The profile has been saved.

**Comment by leider** [comment]
passiert bei mir nicht. Was muss ich tun, um es zu reproduzieren?

**Comment by NicoleRauch** [comment]
Hm, vielleicht pullen? (Evtl. hab ich was kaputtgemacht). Oder mein Rechner spinnt oder so.

**Comment by leider** [comment]
Habe ich und auch auf der SoCraTes Site probiert. Ich schaff es nicht.

**Comment by NicoleRauch** [comment]
Dann ist es vielleicht einfach mein Rechner.
