### ISSUE TITLE
Payment instructions are hard to find

### ISSUE THREAD

**Issue by JeroenDeDauw** [softwerkskammer/Agora#962]
I registered a few days ago and did not immediately make the 100 EUR deposit as I was not sure I'd be able to get an acceptable room. Today I logged into the site again to find the instructions for making this deposit. The `/registration` page mentions a bunch of stuff but does not actually have the required info. I then proceeded to looking at probably all "normal" pages accessible via the menu and searched my email inbox. At the very end I checked my own profile and even clicked "edit profile", not expecting to find anything there.  Just before closing the tab to start writing a mail asking for further instructions, I noticed the save button said "save and pay". Clicking this did take me to a page that had the required information.

**Comment by NicoleRauch** [comment]
Thanks, this is a very valid point!

Can you give us some more details on where exactly you'd prefer to find the information? Should it be on the /registration page - if yes, where exactly? And what other "normal" pages did you consider? Thanks for your help!

**Comment by JeroenDeDauw** [comment]
If having a "make payment" button show up in the main navigation menu when someone registered but did not pay yet, then that'd be quite clear.

**Comment by NicoleRauch** [comment]
There is now a button in the main titlebar:

![screenshot](https://cloud.githubusercontent.com/assets/436499/7554062/2c196e2e-f718-11e4-9442-d68781254ce0.png)

Is this what you had in mind?

**Comment by JeroenDeDauw** [comment]
It is yes. If that was there, I'd definitely not have had issues finding the page.

**Comment by NicoleRauch** [comment]
Thanks! I'll close this issue.
