### ISSUE TITLE
"Ich bin dabei!"-Button in der Benachrichtigungsmail

### ISSUE THREAD

**Issue by danbim** [softwerkskammer/Agora#973]
Es wäre toll wenn der "Ich bin dabei!"-Button schon in der Benachrichtigungsmail wäre so dass man nicht erst auf die Aktivität im Browser wechseln muss. Ich vermute dass dadurch besseres Feedback käme (bei uns kommen meist drei mal so viele wie sich angemeldet haben). Auch sollte die Farbe des Buttons grün sein und ein zweiter in grau für "Zur Aktivität" so dass man sich sofort aufgefordert fühlt drauf zu klicken.

**Comment by leider** [comment]
Hi,
das haben wir kürzlich extra rausgenommen. Grund war, dass wir datenändernde Operationen als POST request haben möchten und dort dein ein csrf token brauchen (Cross Site Request Forging)

Kannst Du bei den Teilnehmern mal fragen, ob sie das wirklich abhält?

**Comment by leider** [comment]
Keine Antwort, also schliesse ich den Issue
